// Auto-generated by Reflect/dsl/generate_ast_cpp.py. DO NOT EDIT!
#pragma once

#include "Luau/DenseHash2.h"
#include <cstdint>
#include <string_view>

namespace Luau
{

enum class ReflectAtom : int16_t
{
    Unknown = -1,
    Access,
    Allocator,
    Annotation,
    AnnotationColonPosition,
    ArgTypes,
    Args,
    ArgsAnnotationColonPositions,
    ArgsCommaPositions,
    ArgumentNameColonPositions,
    ArgumentsCommaPositions,
    AstAttr,
    AstClassMethod,
    AstClassProperty,
    AstComment,
    AstDeclaredExternTypeProperty,
    AstExprBinary,
    AstExprCall,
    AstExprConstantBool,
    AstExprConstantInteger,
    AstExprConstantNil,
    AstExprConstantNumber,
    AstExprConstantString,
    AstExprError,
    AstExprFunction,
    AstExprGlobal,
    AstExprGroup,
    AstExprIfElse,
    AstExprIndexExpr,
    AstExprIndexName,
    AstExprInstantiate,
    AstExprInterpString,
    AstExprLocal,
    AstExprTable,
    AstExprTypeAssertion,
    AstExprUnary,
    AstExprVarargs,
    AstGenericType,
    AstGenericTypePack,
    AstLocal,
    AstStatAssign,
    AstStatBlock,
    AstStatBreak,
    AstStatClass,
    AstStatCompoundAssign,
    AstStatContinue,
    AstStatDeclareExternType,
    AstStatDeclareFunction,
    AstStatDeclareGlobal,
    AstStatError,
    AstStatExpr,
    AstStatFor,
    AstStatForIn,
    AstStatFunction,
    AstStatIf,
    AstStatLocal,
    AstStatLocalFunction,
    AstStatRepeat,
    AstStatReturn,
    AstStatTypeAlias,
    AstStatTypeFunction,
    AstStatWhile,
    AstTableIndexer,
    AstTableItem,
    AstTableProp,
    AstTypeError,
    AstTypeFunction,
    AstTypeGroup,
    AstTypeIntersection,
    AstTypeList,
    AstTypeOptional,
    AstTypePackExplicit,
    AstTypePackGeneric,
    AstTypePackVariadic,
    AstTypeReference,
    AstTypeSingletonBool,
    AstTypeSingletonString,
    AstTypeTable,
    AstTypeTypeof,
    AstTypeUnion,
    Attributes,
    Begin,
    BlockDepth,
    Body,
    Category,
    CategoryAttr,
    CategoryExpr,
    CategoryGeneric,
    CategoryStat,
    CategoryType,
    CategoryTypePack,
    Children,
    CloseArgsPosition,
    CloseBracketPosition,
    CloseGenericsPosition,
    CloseParametersPosition,
    CloseParenPosition,
    CloseParens,
    CloseParenthesesPosition,
    ClosePosition,
    CommaPositions,
    Comments,
    Condition,
    Cst,
    CstAttr,
    CstExprCall,
    CstExprConstantInteger,
    CstExprConstantNumber,
    CstExprConstantString,
    CstExprExplicitTypeInstantiation,
    CstExprFunction,
    CstExprGroup,
    CstExprIfElse,
    CstExprIndexExpr,
    CstExprInterpString,
    CstExprOp,
    CstExprTable,
    CstExprTypeAssertion,
    CstGenericType,
    CstGenericTypePack,
    CstParametrizedAttr,
    CstStatAssign,
    CstStatCompoundAssign,
    CstStatDo,
    CstStatFor,
    CstStatForIn,
    CstStatFunction,
    CstStatLocal,
    CstStatLocalFunction,
    CstStatRepeat,
    CstStatReturn,
    CstStatTypeAlias,
    CstStatTypeFunction,
    CstTableItem,
    CstTypeFunction,
    CstTypeGroup,
    CstTypeIntersection,
    CstTypePackExplicit,
    CstTypePackGeneric,
    CstTypeReference,
    CstTypeSingletonString,
    CstTypeTable,
    CstTypeTypeof,
    CstTypeUnion,
    DebugName,
    DefaultEqualsPosition,
    Defaultnode,
    Depth,
    EllipsisPosition,
    ElseBody,
    ElsePosition,
    End,
    EndCommaPosition,
    EndPosition,
    EqualsPosition,
    Errors,
    Exported,
    Expr,
    Expressions,
    FalseExpr,
    From,
    Func,
    FunctionKeywordPosition,
    GenericPacks,
    Generics,
    GenericsClosePosition,
    GenericsCommaPositions,
    GenericsOpenPosition,
    HasAt,
    HasDo,
    HasElse,
    HasEnd,
    HasErrors,
    HasIn,
    HasParameterList,
    HasSemicolon,
    Id,
    Index,
    IndexType,
    Indexer,
    IndexerClosePosition,
    IndexerOpenPosition,
    IsArray,
    IsConst,
    IsElseIf,
    IsMethod,
    IsMissing,
    Items,
    Key,
    Kind,
    LeadingComments,
    LeadingPosition,
    Left,
    LineOffsets,
    List,
    Local,
    LocalKeywordPosition,
    Matches,
    Members,
    MessageIndex,
    Name,
    Op,
    OpPosition,
    OpenArgsPosition,
    OpenBracketPosition,
    OpenGenericsPosition,
    OpenParametersPosition,
    OpenParenPosition,
    OpenParens,
    OpenParenthesesPosition,
    OpenPosition,
    OrigLocation,
    Parameters,
    ParametersCommaPositions,
    Params,
    Parse,
    Parseexpr,
    Prefix,
    PrefixPointPosition,
    Prettyprint,
    Properties,
    Props,
    QuoteStyle,
    ResultType,
    ReturnAnnotation,
    ReturnArrowPosition,
    ReturnSpecifierPosition,
    ReturnTypes,
    Right,
    Root,
    Self,
    Separator,
    SeparatorPosition,
    SeparatorPositions,
    SetAccess,
    SetAnnotation,
    SetArgTypes,
    SetArgs,
    SetAttributes,
    SetBegin,
    SetBody,
    SetCondition,
    SetDebugName,
    SetDepth,
    SetElseBody,
    SetEnd,
    SetExported,
    SetExpr,
    SetExpressions,
    SetFalseExpr,
    SetFrom,
    SetFunc,
    SetGenericPacks,
    SetGenerics,
    SetHasDo,
    SetHasElse,
    SetHasEnd,
    SetHasErrors,
    SetHasIn,
    SetHasParameterList,
    SetHasSemicolon,
    SetIndex,
    SetIndexType,
    SetIndexer,
    SetIsConst,
    SetIsMethod,
    SetItems,
    SetKey,
    SetKind,
    SetLeadingComments,
    SetLeft,
    SetList,
    SetLocal,
    SetMembers,
    SetName,
    SetOp,
    SetParameters,
    SetParams,
    SetPrefix,
    SetProps,
    SetQuoteStyle,
    SetResultType,
    SetReturnAnnotation,
    SetReturnTypes,
    SetRight,
    SetSelf,
    SetShadow,
    SetStep,
    SetStrings,
    SetSuperName,
    SetTailType,
    SetText,
    SetThenBody,
    SetTo,
    SetTrailingComments,
    SetTrueExpr,
    SetType,
    SetTypeArguments,
    SetTypeList,
    SetTypes,
    SetUpvalue,
    SetValue,
    SetValues,
    SetVar,
    SetVararg,
    SetVariadicType,
    SetVars,
    Shadow,
    Source,
    SourceString,
    Statements,
    StatsStartPosition,
    Step,
    StepCommaPosition,
    Strings,
    SuperName,
    TailType,
    Text,
    ThenBody,
    ThenPosition,
    To,
    TrailingComments,
    TrueExpr,
    Type,
    TypeArguments,
    TypeKeywordPosition,
    TypeList,
    Types,
    UntilPosition,
    Upvalue,
    Value,
    Values,
    ValuesCommaPositions,
    Var,
    Vararg,
    VarargAnnotationColonPosition,
    VariadicType,
    Vars,
    VarsAnnotationColonPositions,
    VarsCommaPositions,
    Walk,
    Count,
};

inline const char* getAtomString(ReflectAtom atom)
{
    switch (atom)
    {
    case ReflectAtom::Access:
        return "access";
    case ReflectAtom::Allocator:
        return "allocator";
    case ReflectAtom::Annotation:
        return "annotation";
    case ReflectAtom::AnnotationColonPosition:
        return "annotationColonPosition";
    case ReflectAtom::ArgTypes:
        return "argTypes";
    case ReflectAtom::Args:
        return "args";
    case ReflectAtom::ArgsAnnotationColonPositions:
        return "argsAnnotationColonPositions";
    case ReflectAtom::ArgsCommaPositions:
        return "argsCommaPositions";
    case ReflectAtom::ArgumentNameColonPositions:
        return "argumentNameColonPositions";
    case ReflectAtom::ArgumentsCommaPositions:
        return "argumentsCommaPositions";
    case ReflectAtom::AstAttr:
        return "AstAttr";
    case ReflectAtom::AstClassMethod:
        return "AstClassMethod";
    case ReflectAtom::AstClassProperty:
        return "AstClassProperty";
    case ReflectAtom::AstComment:
        return "AstComment";
    case ReflectAtom::AstDeclaredExternTypeProperty:
        return "AstDeclaredExternTypeProperty";
    case ReflectAtom::AstExprBinary:
        return "AstExprBinary";
    case ReflectAtom::AstExprCall:
        return "AstExprCall";
    case ReflectAtom::AstExprConstantBool:
        return "AstExprConstantBool";
    case ReflectAtom::AstExprConstantInteger:
        return "AstExprConstantInteger";
    case ReflectAtom::AstExprConstantNil:
        return "AstExprConstantNil";
    case ReflectAtom::AstExprConstantNumber:
        return "AstExprConstantNumber";
    case ReflectAtom::AstExprConstantString:
        return "AstExprConstantString";
    case ReflectAtom::AstExprError:
        return "AstExprError";
    case ReflectAtom::AstExprFunction:
        return "AstExprFunction";
    case ReflectAtom::AstExprGlobal:
        return "AstExprGlobal";
    case ReflectAtom::AstExprGroup:
        return "AstExprGroup";
    case ReflectAtom::AstExprIfElse:
        return "AstExprIfElse";
    case ReflectAtom::AstExprIndexExpr:
        return "AstExprIndexExpr";
    case ReflectAtom::AstExprIndexName:
        return "AstExprIndexName";
    case ReflectAtom::AstExprInstantiate:
        return "AstExprInstantiate";
    case ReflectAtom::AstExprInterpString:
        return "AstExprInterpString";
    case ReflectAtom::AstExprLocal:
        return "AstExprLocal";
    case ReflectAtom::AstExprTable:
        return "AstExprTable";
    case ReflectAtom::AstExprTypeAssertion:
        return "AstExprTypeAssertion";
    case ReflectAtom::AstExprUnary:
        return "AstExprUnary";
    case ReflectAtom::AstExprVarargs:
        return "AstExprVarargs";
    case ReflectAtom::AstGenericType:
        return "AstGenericType";
    case ReflectAtom::AstGenericTypePack:
        return "AstGenericTypePack";
    case ReflectAtom::AstLocal:
        return "AstLocal";
    case ReflectAtom::AstStatAssign:
        return "AstStatAssign";
    case ReflectAtom::AstStatBlock:
        return "AstStatBlock";
    case ReflectAtom::AstStatBreak:
        return "AstStatBreak";
    case ReflectAtom::AstStatClass:
        return "AstStatClass";
    case ReflectAtom::AstStatCompoundAssign:
        return "AstStatCompoundAssign";
    case ReflectAtom::AstStatContinue:
        return "AstStatContinue";
    case ReflectAtom::AstStatDeclareExternType:
        return "AstStatDeclareExternType";
    case ReflectAtom::AstStatDeclareFunction:
        return "AstStatDeclareFunction";
    case ReflectAtom::AstStatDeclareGlobal:
        return "AstStatDeclareGlobal";
    case ReflectAtom::AstStatError:
        return "AstStatError";
    case ReflectAtom::AstStatExpr:
        return "AstStatExpr";
    case ReflectAtom::AstStatFor:
        return "AstStatFor";
    case ReflectAtom::AstStatForIn:
        return "AstStatForIn";
    case ReflectAtom::AstStatFunction:
        return "AstStatFunction";
    case ReflectAtom::AstStatIf:
        return "AstStatIf";
    case ReflectAtom::AstStatLocal:
        return "AstStatLocal";
    case ReflectAtom::AstStatLocalFunction:
        return "AstStatLocalFunction";
    case ReflectAtom::AstStatRepeat:
        return "AstStatRepeat";
    case ReflectAtom::AstStatReturn:
        return "AstStatReturn";
    case ReflectAtom::AstStatTypeAlias:
        return "AstStatTypeAlias";
    case ReflectAtom::AstStatTypeFunction:
        return "AstStatTypeFunction";
    case ReflectAtom::AstStatWhile:
        return "AstStatWhile";
    case ReflectAtom::AstTableIndexer:
        return "AstTableIndexer";
    case ReflectAtom::AstTableItem:
        return "AstTableItem";
    case ReflectAtom::AstTableProp:
        return "AstTableProp";
    case ReflectAtom::AstTypeError:
        return "AstTypeError";
    case ReflectAtom::AstTypeFunction:
        return "AstTypeFunction";
    case ReflectAtom::AstTypeGroup:
        return "AstTypeGroup";
    case ReflectAtom::AstTypeIntersection:
        return "AstTypeIntersection";
    case ReflectAtom::AstTypeList:
        return "AstTypeList";
    case ReflectAtom::AstTypeOptional:
        return "AstTypeOptional";
    case ReflectAtom::AstTypePackExplicit:
        return "AstTypePackExplicit";
    case ReflectAtom::AstTypePackGeneric:
        return "AstTypePackGeneric";
    case ReflectAtom::AstTypePackVariadic:
        return "AstTypePackVariadic";
    case ReflectAtom::AstTypeReference:
        return "AstTypeReference";
    case ReflectAtom::AstTypeSingletonBool:
        return "AstTypeSingletonBool";
    case ReflectAtom::AstTypeSingletonString:
        return "AstTypeSingletonString";
    case ReflectAtom::AstTypeTable:
        return "AstTypeTable";
    case ReflectAtom::AstTypeTypeof:
        return "AstTypeTypeof";
    case ReflectAtom::AstTypeUnion:
        return "AstTypeUnion";
    case ReflectAtom::Attributes:
        return "attributes";
    case ReflectAtom::Begin:
        return "begin";
    case ReflectAtom::BlockDepth:
        return "blockDepth";
    case ReflectAtom::Body:
        return "body";
    case ReflectAtom::Category:
        return "category";
    case ReflectAtom::CategoryAttr:
        return "attr";
    case ReflectAtom::CategoryExpr:
        return "expr";
    case ReflectAtom::CategoryGeneric:
        return "generic";
    case ReflectAtom::CategoryStat:
        return "stat";
    case ReflectAtom::CategoryType:
        return "type";
    case ReflectAtom::CategoryTypePack:
        return "typePack";
    case ReflectAtom::Children:
        return "children";
    case ReflectAtom::CloseArgsPosition:
        return "closeArgsPosition";
    case ReflectAtom::CloseBracketPosition:
        return "closeBracketPosition";
    case ReflectAtom::CloseGenericsPosition:
        return "closeGenericsPosition";
    case ReflectAtom::CloseParametersPosition:
        return "closeParametersPosition";
    case ReflectAtom::CloseParenPosition:
        return "closeParenPosition";
    case ReflectAtom::CloseParens:
        return "closeParens";
    case ReflectAtom::CloseParenthesesPosition:
        return "closeParenthesesPosition";
    case ReflectAtom::ClosePosition:
        return "closePosition";
    case ReflectAtom::CommaPositions:
        return "commaPositions";
    case ReflectAtom::Comments:
        return "comments";
    case ReflectAtom::Condition:
        return "condition";
    case ReflectAtom::Cst:
        return "cst";
    case ReflectAtom::CstAttr:
        return "CstAttr";
    case ReflectAtom::CstExprCall:
        return "CstExprCall";
    case ReflectAtom::CstExprConstantInteger:
        return "CstExprConstantInteger";
    case ReflectAtom::CstExprConstantNumber:
        return "CstExprConstantNumber";
    case ReflectAtom::CstExprConstantString:
        return "CstExprConstantString";
    case ReflectAtom::CstExprExplicitTypeInstantiation:
        return "CstExprExplicitTypeInstantiation";
    case ReflectAtom::CstExprFunction:
        return "CstExprFunction";
    case ReflectAtom::CstExprGroup:
        return "CstExprGroup";
    case ReflectAtom::CstExprIfElse:
        return "CstExprIfElse";
    case ReflectAtom::CstExprIndexExpr:
        return "CstExprIndexExpr";
    case ReflectAtom::CstExprInterpString:
        return "CstExprInterpString";
    case ReflectAtom::CstExprOp:
        return "CstExprOp";
    case ReflectAtom::CstExprTable:
        return "CstExprTable";
    case ReflectAtom::CstExprTypeAssertion:
        return "CstExprTypeAssertion";
    case ReflectAtom::CstGenericType:
        return "CstGenericType";
    case ReflectAtom::CstGenericTypePack:
        return "CstGenericTypePack";
    case ReflectAtom::CstParametrizedAttr:
        return "CstParametrizedAttr";
    case ReflectAtom::CstStatAssign:
        return "CstStatAssign";
    case ReflectAtom::CstStatCompoundAssign:
        return "CstStatCompoundAssign";
    case ReflectAtom::CstStatDo:
        return "CstStatDo";
    case ReflectAtom::CstStatFor:
        return "CstStatFor";
    case ReflectAtom::CstStatForIn:
        return "CstStatForIn";
    case ReflectAtom::CstStatFunction:
        return "CstStatFunction";
    case ReflectAtom::CstStatLocal:
        return "CstStatLocal";
    case ReflectAtom::CstStatLocalFunction:
        return "CstStatLocalFunction";
    case ReflectAtom::CstStatRepeat:
        return "CstStatRepeat";
    case ReflectAtom::CstStatReturn:
        return "CstStatReturn";
    case ReflectAtom::CstStatTypeAlias:
        return "CstStatTypeAlias";
    case ReflectAtom::CstStatTypeFunction:
        return "CstStatTypeFunction";
    case ReflectAtom::CstTableItem:
        return "CstTableItem";
    case ReflectAtom::CstTypeFunction:
        return "CstTypeFunction";
    case ReflectAtom::CstTypeGroup:
        return "CstTypeGroup";
    case ReflectAtom::CstTypeIntersection:
        return "CstTypeIntersection";
    case ReflectAtom::CstTypePackExplicit:
        return "CstTypePackExplicit";
    case ReflectAtom::CstTypePackGeneric:
        return "CstTypePackGeneric";
    case ReflectAtom::CstTypeReference:
        return "CstTypeReference";
    case ReflectAtom::CstTypeSingletonString:
        return "CstTypeSingletonString";
    case ReflectAtom::CstTypeTable:
        return "CstTypeTable";
    case ReflectAtom::CstTypeTypeof:
        return "CstTypeTypeof";
    case ReflectAtom::CstTypeUnion:
        return "CstTypeUnion";
    case ReflectAtom::DebugName:
        return "debugname";
    case ReflectAtom::DefaultEqualsPosition:
        return "defaultEqualsPosition";
    case ReflectAtom::Defaultnode:
        return "defaultnode";
    case ReflectAtom::Depth:
        return "depth";
    case ReflectAtom::EllipsisPosition:
        return "ellipsisPosition";
    case ReflectAtom::ElseBody:
        return "elsebody";
    case ReflectAtom::ElsePosition:
        return "elsePosition";
    case ReflectAtom::End:
        return "end";
    case ReflectAtom::EndCommaPosition:
        return "endCommaPosition";
    case ReflectAtom::EndPosition:
        return "endPosition";
    case ReflectAtom::EqualsPosition:
        return "equalsPosition";
    case ReflectAtom::Errors:
        return "errors";
    case ReflectAtom::Exported:
        return "exported";
    case ReflectAtom::Expr:
        return "expr";
    case ReflectAtom::Expressions:
        return "expressions";
    case ReflectAtom::FalseExpr:
        return "falseExpr";
    case ReflectAtom::From:
        return "from";
    case ReflectAtom::Func:
        return "func";
    case ReflectAtom::FunctionKeywordPosition:
        return "functionKeywordPosition";
    case ReflectAtom::GenericPacks:
        return "genericPacks";
    case ReflectAtom::Generics:
        return "generics";
    case ReflectAtom::GenericsClosePosition:
        return "genericsClosePosition";
    case ReflectAtom::GenericsCommaPositions:
        return "genericsCommaPositions";
    case ReflectAtom::GenericsOpenPosition:
        return "genericsOpenPosition";
    case ReflectAtom::HasAt:
        return "hasAt";
    case ReflectAtom::HasDo:
        return "hasDo";
    case ReflectAtom::HasElse:
        return "hasElse";
    case ReflectAtom::HasEnd:
        return "hasEnd";
    case ReflectAtom::HasErrors:
        return "hasErrors";
    case ReflectAtom::HasIn:
        return "hasIn";
    case ReflectAtom::HasParameterList:
        return "hasParameterList";
    case ReflectAtom::HasSemicolon:
        return "hasSemicolon";
    case ReflectAtom::Id:
        return "id";
    case ReflectAtom::Index:
        return "index";
    case ReflectAtom::IndexType:
        return "indexType";
    case ReflectAtom::Indexer:
        return "indexer";
    case ReflectAtom::IndexerClosePosition:
        return "indexerClosePosition";
    case ReflectAtom::IndexerOpenPosition:
        return "indexerOpenPosition";
    case ReflectAtom::IsArray:
        return "isArray";
    case ReflectAtom::IsConst:
        return "isConst";
    case ReflectAtom::IsElseIf:
        return "isElseIf";
    case ReflectAtom::IsMethod:
        return "isMethod";
    case ReflectAtom::IsMissing:
        return "isMissing";
    case ReflectAtom::Items:
        return "items";
    case ReflectAtom::Key:
        return "key";
    case ReflectAtom::Kind:
        return "kind";
    case ReflectAtom::LeadingComments:
        return "leadingComments";
    case ReflectAtom::LeadingPosition:
        return "leadingPosition";
    case ReflectAtom::Left:
        return "left";
    case ReflectAtom::LineOffsets:
        return "lineOffsets";
    case ReflectAtom::List:
        return "list";
    case ReflectAtom::Local:
        return "local";
    case ReflectAtom::LocalKeywordPosition:
        return "localKeywordPosition";
    case ReflectAtom::Matches:
        return "matches";
    case ReflectAtom::Members:
        return "members";
    case ReflectAtom::MessageIndex:
        return "messageIndex";
    case ReflectAtom::Name:
        return "name";
    case ReflectAtom::Op:
        return "op";
    case ReflectAtom::OpPosition:
        return "opPosition";
    case ReflectAtom::OpenArgsPosition:
        return "openArgsPosition";
    case ReflectAtom::OpenBracketPosition:
        return "openBracketPosition";
    case ReflectAtom::OpenGenericsPosition:
        return "openGenericsPosition";
    case ReflectAtom::OpenParametersPosition:
        return "openParametersPosition";
    case ReflectAtom::OpenParenPosition:
        return "openParenPosition";
    case ReflectAtom::OpenParens:
        return "openParens";
    case ReflectAtom::OpenParenthesesPosition:
        return "openParenthesesPosition";
    case ReflectAtom::OpenPosition:
        return "openPosition";
    case ReflectAtom::OrigLocation:
        return "origlocation";
    case ReflectAtom::Parameters:
        return "parameters";
    case ReflectAtom::ParametersCommaPositions:
        return "parametersCommaPositions";
    case ReflectAtom::Params:
        return "params";
    case ReflectAtom::Parse:
        return "parse";
    case ReflectAtom::Parseexpr:
        return "parseexpr";
    case ReflectAtom::Prefix:
        return "prefix";
    case ReflectAtom::PrefixPointPosition:
        return "prefixPointPosition";
    case ReflectAtom::Prettyprint:
        return "prettyprint";
    case ReflectAtom::Properties:
        return "properties";
    case ReflectAtom::Props:
        return "props";
    case ReflectAtom::QuoteStyle:
        return "quoteStyle";
    case ReflectAtom::ResultType:
        return "resultType";
    case ReflectAtom::ReturnAnnotation:
        return "returnAnnotation";
    case ReflectAtom::ReturnArrowPosition:
        return "returnArrowPosition";
    case ReflectAtom::ReturnSpecifierPosition:
        return "returnSpecifierPosition";
    case ReflectAtom::ReturnTypes:
        return "returnTypes";
    case ReflectAtom::Right:
        return "right";
    case ReflectAtom::Root:
        return "root";
    case ReflectAtom::Self:
        return "self";
    case ReflectAtom::Separator:
        return "separator";
    case ReflectAtom::SeparatorPosition:
        return "separatorPosition";
    case ReflectAtom::SeparatorPositions:
        return "separatorPositions";
    case ReflectAtom::SetAccess:
        return "setAccess";
    case ReflectAtom::SetAnnotation:
        return "setAnnotation";
    case ReflectAtom::SetArgTypes:
        return "setArgTypes";
    case ReflectAtom::SetArgs:
        return "setArgs";
    case ReflectAtom::SetAttributes:
        return "setAttributes";
    case ReflectAtom::SetBegin:
        return "setBegin";
    case ReflectAtom::SetBody:
        return "setBody";
    case ReflectAtom::SetCondition:
        return "setCondition";
    case ReflectAtom::SetDebugName:
        return "setDebugName";
    case ReflectAtom::SetDepth:
        return "setDepth";
    case ReflectAtom::SetElseBody:
        return "setElseBody";
    case ReflectAtom::SetEnd:
        return "setEnd";
    case ReflectAtom::SetExported:
        return "setExported";
    case ReflectAtom::SetExpr:
        return "setExpr";
    case ReflectAtom::SetExpressions:
        return "setExpressions";
    case ReflectAtom::SetFalseExpr:
        return "setFalseExpr";
    case ReflectAtom::SetFrom:
        return "setFrom";
    case ReflectAtom::SetFunc:
        return "setFunc";
    case ReflectAtom::SetGenericPacks:
        return "setGenericPacks";
    case ReflectAtom::SetGenerics:
        return "setGenerics";
    case ReflectAtom::SetHasDo:
        return "setHasDo";
    case ReflectAtom::SetHasElse:
        return "setHasElse";
    case ReflectAtom::SetHasEnd:
        return "setHasEnd";
    case ReflectAtom::SetHasErrors:
        return "setHasErrors";
    case ReflectAtom::SetHasIn:
        return "setHasIn";
    case ReflectAtom::SetHasParameterList:
        return "setHasParameterList";
    case ReflectAtom::SetHasSemicolon:
        return "setHasSemicolon";
    case ReflectAtom::SetIndex:
        return "setIndex";
    case ReflectAtom::SetIndexType:
        return "setIndexType";
    case ReflectAtom::SetIndexer:
        return "setIndexer";
    case ReflectAtom::SetIsConst:
        return "setIsConst";
    case ReflectAtom::SetIsMethod:
        return "setIsMethod";
    case ReflectAtom::SetItems:
        return "setItems";
    case ReflectAtom::SetKey:
        return "setKey";
    case ReflectAtom::SetKind:
        return "setKind";
    case ReflectAtom::SetLeadingComments:
        return "setLeadingComments";
    case ReflectAtom::SetLeft:
        return "setLeft";
    case ReflectAtom::SetList:
        return "setList";
    case ReflectAtom::SetLocal:
        return "setLocal";
    case ReflectAtom::SetMembers:
        return "setMembers";
    case ReflectAtom::SetName:
        return "setName";
    case ReflectAtom::SetOp:
        return "setOp";
    case ReflectAtom::SetParameters:
        return "setParameters";
    case ReflectAtom::SetParams:
        return "setParams";
    case ReflectAtom::SetPrefix:
        return "setPrefix";
    case ReflectAtom::SetProps:
        return "setProps";
    case ReflectAtom::SetQuoteStyle:
        return "setQuoteStyle";
    case ReflectAtom::SetResultType:
        return "setResultType";
    case ReflectAtom::SetReturnAnnotation:
        return "setReturnAnnotation";
    case ReflectAtom::SetReturnTypes:
        return "setReturnTypes";
    case ReflectAtom::SetRight:
        return "setRight";
    case ReflectAtom::SetSelf:
        return "setSelf";
    case ReflectAtom::SetShadow:
        return "setShadow";
    case ReflectAtom::SetStep:
        return "setStep";
    case ReflectAtom::SetStrings:
        return "setStrings";
    case ReflectAtom::SetSuperName:
        return "setSuperName";
    case ReflectAtom::SetTailType:
        return "setTailType";
    case ReflectAtom::SetText:
        return "setText";
    case ReflectAtom::SetThenBody:
        return "setThenBody";
    case ReflectAtom::SetTo:
        return "setTo";
    case ReflectAtom::SetTrailingComments:
        return "setTrailingComments";
    case ReflectAtom::SetTrueExpr:
        return "setTrueExpr";
    case ReflectAtom::SetType:
        return "setType";
    case ReflectAtom::SetTypeArguments:
        return "setTypeArguments";
    case ReflectAtom::SetTypeList:
        return "setTypeList";
    case ReflectAtom::SetTypes:
        return "setTypes";
    case ReflectAtom::SetUpvalue:
        return "setUpvalue";
    case ReflectAtom::SetValue:
        return "setValue";
    case ReflectAtom::SetValues:
        return "setValues";
    case ReflectAtom::SetVar:
        return "setVar";
    case ReflectAtom::SetVararg:
        return "setVararg";
    case ReflectAtom::SetVariadicType:
        return "setVariadicType";
    case ReflectAtom::SetVars:
        return "setVars";
    case ReflectAtom::Shadow:
        return "shadow";
    case ReflectAtom::Source:
        return "source";
    case ReflectAtom::SourceString:
        return "sourceString";
    case ReflectAtom::Statements:
        return "statements";
    case ReflectAtom::StatsStartPosition:
        return "statsStartPosition";
    case ReflectAtom::Step:
        return "step";
    case ReflectAtom::StepCommaPosition:
        return "stepCommaPosition";
    case ReflectAtom::Strings:
        return "strings";
    case ReflectAtom::SuperName:
        return "superName";
    case ReflectAtom::TailType:
        return "tailType";
    case ReflectAtom::Text:
        return "text";
    case ReflectAtom::ThenBody:
        return "thenbody";
    case ReflectAtom::ThenPosition:
        return "thenPosition";
    case ReflectAtom::To:
        return "to";
    case ReflectAtom::TrailingComments:
        return "trailingComments";
    case ReflectAtom::TrueExpr:
        return "trueExpr";
    case ReflectAtom::Type:
        return "type";
    case ReflectAtom::TypeArguments:
        return "typeArguments";
    case ReflectAtom::TypeKeywordPosition:
        return "typeKeywordPosition";
    case ReflectAtom::TypeList:
        return "typeList";
    case ReflectAtom::Types:
        return "types";
    case ReflectAtom::UntilPosition:
        return "untilPosition";
    case ReflectAtom::Upvalue:
        return "upvalue";
    case ReflectAtom::Value:
        return "value";
    case ReflectAtom::Values:
        return "values";
    case ReflectAtom::ValuesCommaPositions:
        return "valuesCommaPositions";
    case ReflectAtom::Var:
        return "var";
    case ReflectAtom::Vararg:
        return "vararg";
    case ReflectAtom::VarargAnnotationColonPosition:
        return "varargAnnotationColonPosition";
    case ReflectAtom::VariadicType:
        return "variadicType";
    case ReflectAtom::Vars:
        return "vars";
    case ReflectAtom::VarsAnnotationColonPositions:
        return "varsAnnotationColonPositions";
    case ReflectAtom::VarsCommaPositions:
        return "varsCommaPositions";
    case ReflectAtom::Walk:
        return "walk";
    default:
        return "";
    }
}

inline ReflectAtom resolveGlobalReflectAtom(std::string_view key)
{
    static const DenseHashMap2<std::string_view, ReflectAtom> s_atomMap = []() {
        DenseHashMap2<std::string_view, ReflectAtom> map;
        map["AstAttr"] = ReflectAtom::AstAttr;
        map["AstClassMethod"] = ReflectAtom::AstClassMethod;
        map["AstClassProperty"] = ReflectAtom::AstClassProperty;
        map["AstComment"] = ReflectAtom::AstComment;
        map["AstDeclaredExternTypeProperty"] = ReflectAtom::AstDeclaredExternTypeProperty;
        map["AstExprBinary"] = ReflectAtom::AstExprBinary;
        map["AstExprCall"] = ReflectAtom::AstExprCall;
        map["AstExprConstantBool"] = ReflectAtom::AstExprConstantBool;
        map["AstExprConstantInteger"] = ReflectAtom::AstExprConstantInteger;
        map["AstExprConstantNil"] = ReflectAtom::AstExprConstantNil;
        map["AstExprConstantNumber"] = ReflectAtom::AstExprConstantNumber;
        map["AstExprConstantString"] = ReflectAtom::AstExprConstantString;
        map["AstExprError"] = ReflectAtom::AstExprError;
        map["AstExprFunction"] = ReflectAtom::AstExprFunction;
        map["AstExprGlobal"] = ReflectAtom::AstExprGlobal;
        map["AstExprGroup"] = ReflectAtom::AstExprGroup;
        map["AstExprIfElse"] = ReflectAtom::AstExprIfElse;
        map["AstExprIndexExpr"] = ReflectAtom::AstExprIndexExpr;
        map["AstExprIndexName"] = ReflectAtom::AstExprIndexName;
        map["AstExprInstantiate"] = ReflectAtom::AstExprInstantiate;
        map["AstExprInterpString"] = ReflectAtom::AstExprInterpString;
        map["AstExprLocal"] = ReflectAtom::AstExprLocal;
        map["AstExprTable"] = ReflectAtom::AstExprTable;
        map["AstExprTypeAssertion"] = ReflectAtom::AstExprTypeAssertion;
        map["AstExprUnary"] = ReflectAtom::AstExprUnary;
        map["AstExprVarargs"] = ReflectAtom::AstExprVarargs;
        map["AstGenericType"] = ReflectAtom::AstGenericType;
        map["AstGenericTypePack"] = ReflectAtom::AstGenericTypePack;
        map["AstLocal"] = ReflectAtom::AstLocal;
        map["AstStatAssign"] = ReflectAtom::AstStatAssign;
        map["AstStatBlock"] = ReflectAtom::AstStatBlock;
        map["AstStatBreak"] = ReflectAtom::AstStatBreak;
        map["AstStatClass"] = ReflectAtom::AstStatClass;
        map["AstStatCompoundAssign"] = ReflectAtom::AstStatCompoundAssign;
        map["AstStatContinue"] = ReflectAtom::AstStatContinue;
        map["AstStatDeclareExternType"] = ReflectAtom::AstStatDeclareExternType;
        map["AstStatDeclareFunction"] = ReflectAtom::AstStatDeclareFunction;
        map["AstStatDeclareGlobal"] = ReflectAtom::AstStatDeclareGlobal;
        map["AstStatError"] = ReflectAtom::AstStatError;
        map["AstStatExpr"] = ReflectAtom::AstStatExpr;
        map["AstStatFor"] = ReflectAtom::AstStatFor;
        map["AstStatForIn"] = ReflectAtom::AstStatForIn;
        map["AstStatFunction"] = ReflectAtom::AstStatFunction;
        map["AstStatIf"] = ReflectAtom::AstStatIf;
        map["AstStatLocal"] = ReflectAtom::AstStatLocal;
        map["AstStatLocalFunction"] = ReflectAtom::AstStatLocalFunction;
        map["AstStatRepeat"] = ReflectAtom::AstStatRepeat;
        map["AstStatReturn"] = ReflectAtom::AstStatReturn;
        map["AstStatTypeAlias"] = ReflectAtom::AstStatTypeAlias;
        map["AstStatTypeFunction"] = ReflectAtom::AstStatTypeFunction;
        map["AstStatWhile"] = ReflectAtom::AstStatWhile;
        map["AstTableIndexer"] = ReflectAtom::AstTableIndexer;
        map["AstTableItem"] = ReflectAtom::AstTableItem;
        map["AstTableProp"] = ReflectAtom::AstTableProp;
        map["AstTypeError"] = ReflectAtom::AstTypeError;
        map["AstTypeFunction"] = ReflectAtom::AstTypeFunction;
        map["AstTypeGroup"] = ReflectAtom::AstTypeGroup;
        map["AstTypeIntersection"] = ReflectAtom::AstTypeIntersection;
        map["AstTypeList"] = ReflectAtom::AstTypeList;
        map["AstTypeOptional"] = ReflectAtom::AstTypeOptional;
        map["AstTypePackExplicit"] = ReflectAtom::AstTypePackExplicit;
        map["AstTypePackGeneric"] = ReflectAtom::AstTypePackGeneric;
        map["AstTypePackVariadic"] = ReflectAtom::AstTypePackVariadic;
        map["AstTypeReference"] = ReflectAtom::AstTypeReference;
        map["AstTypeSingletonBool"] = ReflectAtom::AstTypeSingletonBool;
        map["AstTypeSingletonString"] = ReflectAtom::AstTypeSingletonString;
        map["AstTypeTable"] = ReflectAtom::AstTypeTable;
        map["AstTypeTypeof"] = ReflectAtom::AstTypeTypeof;
        map["AstTypeUnion"] = ReflectAtom::AstTypeUnion;
        map["CstAttr"] = ReflectAtom::CstAttr;
        map["CstExprCall"] = ReflectAtom::CstExprCall;
        map["CstExprConstantInteger"] = ReflectAtom::CstExprConstantInteger;
        map["CstExprConstantNumber"] = ReflectAtom::CstExprConstantNumber;
        map["CstExprConstantString"] = ReflectAtom::CstExprConstantString;
        map["CstExprExplicitTypeInstantiation"] = ReflectAtom::CstExprExplicitTypeInstantiation;
        map["CstExprFunction"] = ReflectAtom::CstExprFunction;
        map["CstExprGroup"] = ReflectAtom::CstExprGroup;
        map["CstExprIfElse"] = ReflectAtom::CstExprIfElse;
        map["CstExprIndexExpr"] = ReflectAtom::CstExprIndexExpr;
        map["CstExprInterpString"] = ReflectAtom::CstExprInterpString;
        map["CstExprOp"] = ReflectAtom::CstExprOp;
        map["CstExprTable"] = ReflectAtom::CstExprTable;
        map["CstExprTypeAssertion"] = ReflectAtom::CstExprTypeAssertion;
        map["CstGenericType"] = ReflectAtom::CstGenericType;
        map["CstGenericTypePack"] = ReflectAtom::CstGenericTypePack;
        map["CstParametrizedAttr"] = ReflectAtom::CstParametrizedAttr;
        map["CstStatAssign"] = ReflectAtom::CstStatAssign;
        map["CstStatCompoundAssign"] = ReflectAtom::CstStatCompoundAssign;
        map["CstStatDo"] = ReflectAtom::CstStatDo;
        map["CstStatFor"] = ReflectAtom::CstStatFor;
        map["CstStatForIn"] = ReflectAtom::CstStatForIn;
        map["CstStatFunction"] = ReflectAtom::CstStatFunction;
        map["CstStatLocal"] = ReflectAtom::CstStatLocal;
        map["CstStatLocalFunction"] = ReflectAtom::CstStatLocalFunction;
        map["CstStatRepeat"] = ReflectAtom::CstStatRepeat;
        map["CstStatReturn"] = ReflectAtom::CstStatReturn;
        map["CstStatTypeAlias"] = ReflectAtom::CstStatTypeAlias;
        map["CstStatTypeFunction"] = ReflectAtom::CstStatTypeFunction;
        map["CstTableItem"] = ReflectAtom::CstTableItem;
        map["CstTypeFunction"] = ReflectAtom::CstTypeFunction;
        map["CstTypeGroup"] = ReflectAtom::CstTypeGroup;
        map["CstTypeIntersection"] = ReflectAtom::CstTypeIntersection;
        map["CstTypePackExplicit"] = ReflectAtom::CstTypePackExplicit;
        map["CstTypePackGeneric"] = ReflectAtom::CstTypePackGeneric;
        map["CstTypeReference"] = ReflectAtom::CstTypeReference;
        map["CstTypeSingletonString"] = ReflectAtom::CstTypeSingletonString;
        map["CstTypeTable"] = ReflectAtom::CstTypeTable;
        map["CstTypeTypeof"] = ReflectAtom::CstTypeTypeof;
        map["CstTypeUnion"] = ReflectAtom::CstTypeUnion;
        map["access"] = ReflectAtom::Access;
        map["allocator"] = ReflectAtom::Allocator;
        map["annotation"] = ReflectAtom::Annotation;
        map["annotationColonPosition"] = ReflectAtom::AnnotationColonPosition;
        map["argTypes"] = ReflectAtom::ArgTypes;
        map["args"] = ReflectAtom::Args;
        map["argsAnnotationColonPositions"] = ReflectAtom::ArgsAnnotationColonPositions;
        map["argsCommaPositions"] = ReflectAtom::ArgsCommaPositions;
        map["argumentNameColonPositions"] = ReflectAtom::ArgumentNameColonPositions;
        map["argumentsCommaPositions"] = ReflectAtom::ArgumentsCommaPositions;
        map["attr"] = ReflectAtom::CategoryAttr;
        map["attributes"] = ReflectAtom::Attributes;
        map["begin"] = ReflectAtom::Begin;
        map["blockDepth"] = ReflectAtom::BlockDepth;
        map["body"] = ReflectAtom::Body;
        map["category"] = ReflectAtom::Category;
        map["children"] = ReflectAtom::Children;
        map["closeArgsPosition"] = ReflectAtom::CloseArgsPosition;
        map["closeBracketPosition"] = ReflectAtom::CloseBracketPosition;
        map["closeGenericsPosition"] = ReflectAtom::CloseGenericsPosition;
        map["closeParametersPosition"] = ReflectAtom::CloseParametersPosition;
        map["closeParenPosition"] = ReflectAtom::CloseParenPosition;
        map["closeParens"] = ReflectAtom::CloseParens;
        map["closeParenthesesPosition"] = ReflectAtom::CloseParenthesesPosition;
        map["closePosition"] = ReflectAtom::ClosePosition;
        map["commaPositions"] = ReflectAtom::CommaPositions;
        map["comments"] = ReflectAtom::Comments;
        map["condition"] = ReflectAtom::Condition;
        map["cst"] = ReflectAtom::Cst;
        map["debugname"] = ReflectAtom::DebugName;
        map["defaultEqualsPosition"] = ReflectAtom::DefaultEqualsPosition;
        map["defaultnode"] = ReflectAtom::Defaultnode;
        map["depth"] = ReflectAtom::Depth;
        map["ellipsisPosition"] = ReflectAtom::EllipsisPosition;
        map["elsePosition"] = ReflectAtom::ElsePosition;
        map["elsebody"] = ReflectAtom::ElseBody;
        map["end"] = ReflectAtom::End;
        map["endCommaPosition"] = ReflectAtom::EndCommaPosition;
        map["endPosition"] = ReflectAtom::EndPosition;
        map["equalsPosition"] = ReflectAtom::EqualsPosition;
        map["errors"] = ReflectAtom::Errors;
        map["exported"] = ReflectAtom::Exported;
        map["expr"] = ReflectAtom::Expr;
        map["expressions"] = ReflectAtom::Expressions;
        map["falseExpr"] = ReflectAtom::FalseExpr;
        map["from"] = ReflectAtom::From;
        map["func"] = ReflectAtom::Func;
        map["functionKeywordPosition"] = ReflectAtom::FunctionKeywordPosition;
        map["generic"] = ReflectAtom::CategoryGeneric;
        map["genericPacks"] = ReflectAtom::GenericPacks;
        map["generics"] = ReflectAtom::Generics;
        map["genericsClosePosition"] = ReflectAtom::GenericsClosePosition;
        map["genericsCommaPositions"] = ReflectAtom::GenericsCommaPositions;
        map["genericsOpenPosition"] = ReflectAtom::GenericsOpenPosition;
        map["hasAt"] = ReflectAtom::HasAt;
        map["hasDo"] = ReflectAtom::HasDo;
        map["hasElse"] = ReflectAtom::HasElse;
        map["hasEnd"] = ReflectAtom::HasEnd;
        map["hasErrors"] = ReflectAtom::HasErrors;
        map["hasIn"] = ReflectAtom::HasIn;
        map["hasParameterList"] = ReflectAtom::HasParameterList;
        map["hasSemicolon"] = ReflectAtom::HasSemicolon;
        map["id"] = ReflectAtom::Id;
        map["index"] = ReflectAtom::Index;
        map["indexType"] = ReflectAtom::IndexType;
        map["indexer"] = ReflectAtom::Indexer;
        map["indexerClosePosition"] = ReflectAtom::IndexerClosePosition;
        map["indexerOpenPosition"] = ReflectAtom::IndexerOpenPosition;
        map["isArray"] = ReflectAtom::IsArray;
        map["isConst"] = ReflectAtom::IsConst;
        map["isElseIf"] = ReflectAtom::IsElseIf;
        map["isMethod"] = ReflectAtom::IsMethod;
        map["isMissing"] = ReflectAtom::IsMissing;
        map["items"] = ReflectAtom::Items;
        map["key"] = ReflectAtom::Key;
        map["kind"] = ReflectAtom::Kind;
        map["leadingComments"] = ReflectAtom::LeadingComments;
        map["leadingPosition"] = ReflectAtom::LeadingPosition;
        map["left"] = ReflectAtom::Left;
        map["lineOffsets"] = ReflectAtom::LineOffsets;
        map["list"] = ReflectAtom::List;
        map["local"] = ReflectAtom::Local;
        map["localKeywordPosition"] = ReflectAtom::LocalKeywordPosition;
        map["matches"] = ReflectAtom::Matches;
        map["members"] = ReflectAtom::Members;
        map["messageIndex"] = ReflectAtom::MessageIndex;
        map["name"] = ReflectAtom::Name;
        map["op"] = ReflectAtom::Op;
        map["opPosition"] = ReflectAtom::OpPosition;
        map["openArgsPosition"] = ReflectAtom::OpenArgsPosition;
        map["openBracketPosition"] = ReflectAtom::OpenBracketPosition;
        map["openGenericsPosition"] = ReflectAtom::OpenGenericsPosition;
        map["openParametersPosition"] = ReflectAtom::OpenParametersPosition;
        map["openParenPosition"] = ReflectAtom::OpenParenPosition;
        map["openParens"] = ReflectAtom::OpenParens;
        map["openParenthesesPosition"] = ReflectAtom::OpenParenthesesPosition;
        map["openPosition"] = ReflectAtom::OpenPosition;
        map["origlocation"] = ReflectAtom::OrigLocation;
        map["parameters"] = ReflectAtom::Parameters;
        map["parametersCommaPositions"] = ReflectAtom::ParametersCommaPositions;
        map["params"] = ReflectAtom::Params;
        map["parse"] = ReflectAtom::Parse;
        map["parseexpr"] = ReflectAtom::Parseexpr;
        map["prefix"] = ReflectAtom::Prefix;
        map["prefixPointPosition"] = ReflectAtom::PrefixPointPosition;
        map["prettyprint"] = ReflectAtom::Prettyprint;
        map["properties"] = ReflectAtom::Properties;
        map["props"] = ReflectAtom::Props;
        map["quoteStyle"] = ReflectAtom::QuoteStyle;
        map["resultType"] = ReflectAtom::ResultType;
        map["returnAnnotation"] = ReflectAtom::ReturnAnnotation;
        map["returnArrowPosition"] = ReflectAtom::ReturnArrowPosition;
        map["returnSpecifierPosition"] = ReflectAtom::ReturnSpecifierPosition;
        map["returnTypes"] = ReflectAtom::ReturnTypes;
        map["right"] = ReflectAtom::Right;
        map["root"] = ReflectAtom::Root;
        map["self"] = ReflectAtom::Self;
        map["separator"] = ReflectAtom::Separator;
        map["separatorPosition"] = ReflectAtom::SeparatorPosition;
        map["separatorPositions"] = ReflectAtom::SeparatorPositions;
        map["setAccess"] = ReflectAtom::SetAccess;
        map["setAnnotation"] = ReflectAtom::SetAnnotation;
        map["setArgTypes"] = ReflectAtom::SetArgTypes;
        map["setArgs"] = ReflectAtom::SetArgs;
        map["setAttributes"] = ReflectAtom::SetAttributes;
        map["setBegin"] = ReflectAtom::SetBegin;
        map["setBody"] = ReflectAtom::SetBody;
        map["setCondition"] = ReflectAtom::SetCondition;
        map["setDebugName"] = ReflectAtom::SetDebugName;
        map["setDepth"] = ReflectAtom::SetDepth;
        map["setElseBody"] = ReflectAtom::SetElseBody;
        map["setEnd"] = ReflectAtom::SetEnd;
        map["setExported"] = ReflectAtom::SetExported;
        map["setExpr"] = ReflectAtom::SetExpr;
        map["setExpressions"] = ReflectAtom::SetExpressions;
        map["setFalseExpr"] = ReflectAtom::SetFalseExpr;
        map["setFrom"] = ReflectAtom::SetFrom;
        map["setFunc"] = ReflectAtom::SetFunc;
        map["setGenericPacks"] = ReflectAtom::SetGenericPacks;
        map["setGenerics"] = ReflectAtom::SetGenerics;
        map["setHasDo"] = ReflectAtom::SetHasDo;
        map["setHasElse"] = ReflectAtom::SetHasElse;
        map["setHasEnd"] = ReflectAtom::SetHasEnd;
        map["setHasErrors"] = ReflectAtom::SetHasErrors;
        map["setHasIn"] = ReflectAtom::SetHasIn;
        map["setHasParameterList"] = ReflectAtom::SetHasParameterList;
        map["setHasSemicolon"] = ReflectAtom::SetHasSemicolon;
        map["setIndex"] = ReflectAtom::SetIndex;
        map["setIndexType"] = ReflectAtom::SetIndexType;
        map["setIndexer"] = ReflectAtom::SetIndexer;
        map["setIsConst"] = ReflectAtom::SetIsConst;
        map["setIsMethod"] = ReflectAtom::SetIsMethod;
        map["setItems"] = ReflectAtom::SetItems;
        map["setKey"] = ReflectAtom::SetKey;
        map["setKind"] = ReflectAtom::SetKind;
        map["setLeadingComments"] = ReflectAtom::SetLeadingComments;
        map["setLeft"] = ReflectAtom::SetLeft;
        map["setList"] = ReflectAtom::SetList;
        map["setLocal"] = ReflectAtom::SetLocal;
        map["setMembers"] = ReflectAtom::SetMembers;
        map["setName"] = ReflectAtom::SetName;
        map["setOp"] = ReflectAtom::SetOp;
        map["setParameters"] = ReflectAtom::SetParameters;
        map["setParams"] = ReflectAtom::SetParams;
        map["setPrefix"] = ReflectAtom::SetPrefix;
        map["setProps"] = ReflectAtom::SetProps;
        map["setQuoteStyle"] = ReflectAtom::SetQuoteStyle;
        map["setResultType"] = ReflectAtom::SetResultType;
        map["setReturnAnnotation"] = ReflectAtom::SetReturnAnnotation;
        map["setReturnTypes"] = ReflectAtom::SetReturnTypes;
        map["setRight"] = ReflectAtom::SetRight;
        map["setSelf"] = ReflectAtom::SetSelf;
        map["setShadow"] = ReflectAtom::SetShadow;
        map["setStep"] = ReflectAtom::SetStep;
        map["setStrings"] = ReflectAtom::SetStrings;
        map["setSuperName"] = ReflectAtom::SetSuperName;
        map["setTailType"] = ReflectAtom::SetTailType;
        map["setText"] = ReflectAtom::SetText;
        map["setThenBody"] = ReflectAtom::SetThenBody;
        map["setTo"] = ReflectAtom::SetTo;
        map["setTrailingComments"] = ReflectAtom::SetTrailingComments;
        map["setTrueExpr"] = ReflectAtom::SetTrueExpr;
        map["setType"] = ReflectAtom::SetType;
        map["setTypeArguments"] = ReflectAtom::SetTypeArguments;
        map["setTypeList"] = ReflectAtom::SetTypeList;
        map["setTypes"] = ReflectAtom::SetTypes;
        map["setUpvalue"] = ReflectAtom::SetUpvalue;
        map["setValue"] = ReflectAtom::SetValue;
        map["setValues"] = ReflectAtom::SetValues;
        map["setVar"] = ReflectAtom::SetVar;
        map["setVararg"] = ReflectAtom::SetVararg;
        map["setVariadicType"] = ReflectAtom::SetVariadicType;
        map["setVars"] = ReflectAtom::SetVars;
        map["shadow"] = ReflectAtom::Shadow;
        map["source"] = ReflectAtom::Source;
        map["sourceString"] = ReflectAtom::SourceString;
        map["stat"] = ReflectAtom::CategoryStat;
        map["statements"] = ReflectAtom::Statements;
        map["statsStartPosition"] = ReflectAtom::StatsStartPosition;
        map["step"] = ReflectAtom::Step;
        map["stepCommaPosition"] = ReflectAtom::StepCommaPosition;
        map["strings"] = ReflectAtom::Strings;
        map["superName"] = ReflectAtom::SuperName;
        map["tailType"] = ReflectAtom::TailType;
        map["text"] = ReflectAtom::Text;
        map["thenPosition"] = ReflectAtom::ThenPosition;
        map["thenbody"] = ReflectAtom::ThenBody;
        map["to"] = ReflectAtom::To;
        map["trailingComments"] = ReflectAtom::TrailingComments;
        map["trueExpr"] = ReflectAtom::TrueExpr;
        map["type"] = ReflectAtom::Type;
        map["typeArguments"] = ReflectAtom::TypeArguments;
        map["typeKeywordPosition"] = ReflectAtom::TypeKeywordPosition;
        map["typeList"] = ReflectAtom::TypeList;
        map["typePack"] = ReflectAtom::CategoryTypePack;
        map["types"] = ReflectAtom::Types;
        map["untilPosition"] = ReflectAtom::UntilPosition;
        map["upvalue"] = ReflectAtom::Upvalue;
        map["value"] = ReflectAtom::Value;
        map["values"] = ReflectAtom::Values;
        map["valuesCommaPositions"] = ReflectAtom::ValuesCommaPositions;
        map["var"] = ReflectAtom::Var;
        map["vararg"] = ReflectAtom::Vararg;
        map["varargAnnotationColonPosition"] = ReflectAtom::VarargAnnotationColonPosition;
        map["variadicType"] = ReflectAtom::VariadicType;
        map["vars"] = ReflectAtom::Vars;
        map["varsAnnotationColonPositions"] = ReflectAtom::VarsAnnotationColonPositions;
        map["varsCommaPositions"] = ReflectAtom::VarsCommaPositions;
        map["walk"] = ReflectAtom::Walk;
        return map;
    }();

    if (const ReflectAtom* atom = s_atomMap.find(key))
    {
        return *atom;
    }

    return ReflectAtom::Unknown;
}

inline ReflectAtom resolveReflectAtom(int atomId, std::string_view key)
{
    if (atomId >= 0)
    {
        if (atomId < int(ReflectAtom::Count))
        {
            return ReflectAtom(atomId);
        }
        return ReflectAtom::Unknown;
    }
    return resolveGlobalReflectAtom(key);
}

inline ReflectAtom resolveReflectAtom(int atomId, const char* str, size_t len)
{
    if (atomId >= 0)
    {
        if (atomId < int(ReflectAtom::Count))
        {
            return ReflectAtom(atomId);
        }
        return ReflectAtom::Unknown;
    }
    return resolveGlobalReflectAtom(std::string_view(str, len));
}

} // namespace Luau
