// Auto-generated by Reflect/dsl/generate_ast_cpp.py. DO NOT EDIT!
#pragma once

#include "Luau/Ast.h"
#include "Luau/Cst.h"
#include "Luau/ReflectCommon.h"
#include "Luau/ReflectAstHandler.h"

namespace Luau
{

bool createDefaultAstAux(ReflectAtom atom, const std::shared_ptr<AstDocumentState>& doc, AstAuxData& out)
{
    switch (atom)
    {
    case ReflectAtom::AstTableProp:
        out = AstAuxData(doc, Luau::AstTableProp{Luau::AstName(), Luau::Location(), nullptr, Luau::AstTableAccess::ReadWrite, std::nullopt});
        return true;
    case ReflectAtom::AstTableIndexer:
        out = AstAuxData(doc, Luau::AstTableIndexer{nullptr, nullptr, Luau::Location(), Luau::AstTableAccess::ReadWrite, std::nullopt});
        return true;
    case ReflectAtom::AstDeclaredExternTypeProperty:
        out = AstAuxData(doc, Luau::AstDeclaredExternTypeProperty{Luau::AstName(), Luau::Location(), nullptr, false, Luau::Location(), Luau::AstTableAccess::ReadWrite});
        return true;
    case ReflectAtom::AstClassProperty:
        out = AstAuxData(doc, Luau::AstClassProperty{Luau::Location(), Luau::AstName(), Luau::Location(), std::nullopt, nullptr});
        return true;
    case ReflectAtom::AstClassMethod:
        out = AstAuxData(doc, Luau::AstClassMethod{std::nullopt, Luau::Location(), Luau::AstName(), Luau::Location(), nullptr});
        return true;
    case ReflectAtom::AstComment:
        out = AstAuxData(doc, ReflectComment{Luau::Lexeme::Type::Comment, "--", Luau::Location()});
        return true;
    case ReflectAtom::AstTableItem:
        out = AstAuxData(doc, Luau::AstExprTable::Item{Luau::AstExprTable::Item::Kind::List, nullptr, nullptr});
        return true;
    case ReflectAtom::AstTypeList:
        out = AstAuxData(doc, Luau::AstTypeList{Luau::AstArray<Luau::AstType*>{nullptr, 0}, nullptr});
        return true;
    case ReflectAtom::CstTableItem:
        out = AstAuxData(doc, Luau::CstExprTable::Item{Luau::Position::missing(), Luau::Position::missing(), Luau::Position::missing(), Luau::CstExprTable::Separator::Missing, Luau::Position::missing()});
        return true;
    default:
        return false;
    }
}

static bool dispatchAux(lua_State* L, AstAuxData& handle, ReflectAtom atom)
{
    switch (handle.kind)
    {
    case Aux_TableProp:
    {
        auto& n = handle.tableProp;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Name:
            pushReflectValue(L, handle.doc, n.name);
            return true;
        case ReflectAtom::SetName:
            readReflectValue(L, handle.doc, 2, n.name);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::OrigLocation:
            pushReflectValue(L, handle.doc, n.location);
            return true;
        case ReflectAtom::Type:
            pushReflectValue(L, handle.doc, n.type);
            return true;
        case ReflectAtom::SetType:
            readReflectValue(L, handle.doc, 2, n.type);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Access:
            pushReflectValue(L, handle.doc, n.access);
            return true;
        case ReflectAtom::SetAccess:
            readReflectValue(L, handle.doc, 2, n.access);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_TableIndexer:
    {
        auto& n = handle.tableIndexer;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::OrigLocation:
            pushReflectValue(L, handle.doc, n.location);
            return true;
        case ReflectAtom::IndexType:
            pushReflectValue(L, handle.doc, n.indexType);
            return true;
        case ReflectAtom::SetIndexType:
            readReflectValue(L, handle.doc, 2, n.indexType);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::ResultType:
            pushReflectValue(L, handle.doc, n.resultType);
            return true;
        case ReflectAtom::SetResultType:
            readReflectValue(L, handle.doc, 2, n.resultType);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Access:
            pushReflectValue(L, handle.doc, n.access);
            return true;
        case ReflectAtom::SetAccess:
            readReflectValue(L, handle.doc, 2, n.access);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_DeclaredExternTypeProperty:
    {
        auto& n = handle.declaredExternProp;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Name:
            pushReflectValue(L, handle.doc, n.name);
            return true;
        case ReflectAtom::SetName:
            readReflectValue(L, handle.doc, 2, n.name);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::OrigLocation:
            pushReflectValue(L, handle.doc, n.location);
            return true;
        case ReflectAtom::Type:
            pushReflectValue(L, handle.doc, n.ty);
            return true;
        case ReflectAtom::SetType:
            readReflectValue(L, handle.doc, 2, n.ty);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::IsMethod:
            pushReflectValue(L, handle.doc, n.isMethod);
            return true;
        case ReflectAtom::SetIsMethod:
            readReflectValue(L, handle.doc, 2, n.isMethod);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Access:
            pushReflectValue(L, handle.doc, n.access);
            return true;
        case ReflectAtom::SetAccess:
            readReflectValue(L, handle.doc, 2, n.access);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_ClassProperty:
    {
        auto& n = handle.classProp;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Name:
            pushReflectValue(L, handle.doc, n.name);
            return true;
        case ReflectAtom::SetName:
            readReflectValue(L, handle.doc, 2, n.name);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Type:
            pushReflectValue(L, handle.doc, n.ty);
            return true;
        case ReflectAtom::SetType:
            readReflectValue(L, handle.doc, 2, n.ty);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_ClassMethod:
    {
        auto& n = handle.classMethod;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Name:
            pushReflectValue(L, handle.doc, n.functionName);
            return true;
        case ReflectAtom::SetName:
            readReflectValue(L, handle.doc, 2, n.functionName);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Func:
            pushReflectValue(L, handle.doc, n.function);
            return true;
        case ReflectAtom::SetFunc:
            readReflectValue(L, handle.doc, 2, n.function);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_Comment:
    {
        auto& n = handle.comment;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Type:
            pushReflectValue(L, handle.doc, handle.comment.type);
            return true;
        case ReflectAtom::SetType:
            readReflectValue(L, handle.doc, 2, handle.comment.type);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Text:
            pushReflectValue(L, handle.doc, handle.comment.text);
            return true;
        case ReflectAtom::SetText:
            readReflectValue(L, handle.doc, 2, handle.comment.text);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::OrigLocation:
            pushReflectValue(L, handle.doc, handle.comment.location);
            return true;
        default:
            return false;
        }
    }
    case Aux_TableItem:
    {
        auto& n = handle.tableItem;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Key:
            pushReflectValue(L, handle.doc, n.key);
            return true;
        case ReflectAtom::SetKey:
            readReflectValue(L, handle.doc, 2, n.key);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Value:
            pushReflectValue(L, handle.doc, n.value);
            return true;
        case ReflectAtom::SetValue:
            readReflectValue(L, handle.doc, 2, n.value);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::Kind:
            pushReflectValue(L, handle.doc, n.kind);
            return true;
        case ReflectAtom::SetKind:
            readReflectValue(L, handle.doc, 2, n.kind);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_TypeList:
    {
        auto& n = handle.typeList;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::Types:
            pushReflectValue(L, handle.doc, n.types);
            return true;
        case ReflectAtom::SetTypes:
            readReflectValue(L, handle.doc, 2, n.types);
            lua_pushvalue(L, 1);
            return true;
        case ReflectAtom::TailType:
            pushReflectValue(L, handle.doc, n.tailType);
            return true;
        case ReflectAtom::SetTailType:
            readReflectValue(L, handle.doc, 2, n.tailType);
            lua_pushvalue(L, 1);
            return true;
        default:
            return false;
        }
    }
    case Aux_CstTableItem:
    {
        auto& n = handle.cstTableItem;
        (void)n;
        switch (atom)
        {
        case ReflectAtom::IndexerOpenPosition:
            pushReflectValue(L, handle.doc, n.indexerOpenPosition);
            return true;
        case ReflectAtom::IndexerClosePosition:
            pushReflectValue(L, handle.doc, n.indexerClosePosition);
            return true;
        case ReflectAtom::EqualsPosition:
            pushReflectValue(L, handle.doc, n.equalsPosition);
            return true;
        case ReflectAtom::SeparatorPosition:
            pushReflectValue(L, handle.doc, n.separatorPosition);
            return true;
        case ReflectAtom::Separator:
            pushReflectValue(L, handle.doc, n.separator);
            return true;
        default:
            return false;
        }
    }
    default:
        return false;
    }
}

static void collectAuxProps(lua_State* L, AstAuxData& handle)
{
    switch (handle.kind)
    {
    case Aux_TableProp:
    {
        auto& n = handle.tableProp;
        (void)n;
        pushReflectValue(L, handle.doc, n.name);
        lua_setfield(L, -2, "name");
        pushReflectValue(L, handle.doc, n.location);
        lua_setfield(L, -2, "origlocation");
        pushReflectValue(L, handle.doc, n.type);
        lua_setfield(L, -2, "type");
        pushReflectValue(L, handle.doc, n.access);
        lua_setfield(L, -2, "access");
        break;
    }
    case Aux_TableIndexer:
    {
        auto& n = handle.tableIndexer;
        (void)n;
        pushReflectValue(L, handle.doc, n.location);
        lua_setfield(L, -2, "origlocation");
        pushReflectValue(L, handle.doc, n.indexType);
        lua_setfield(L, -2, "indexType");
        pushReflectValue(L, handle.doc, n.resultType);
        lua_setfield(L, -2, "resultType");
        pushReflectValue(L, handle.doc, n.access);
        lua_setfield(L, -2, "access");
        break;
    }
    case Aux_DeclaredExternTypeProperty:
    {
        auto& n = handle.declaredExternProp;
        (void)n;
        pushReflectValue(L, handle.doc, n.name);
        lua_setfield(L, -2, "name");
        pushReflectValue(L, handle.doc, n.location);
        lua_setfield(L, -2, "origlocation");
        pushReflectValue(L, handle.doc, n.ty);
        lua_setfield(L, -2, "type");
        pushReflectValue(L, handle.doc, n.isMethod);
        lua_setfield(L, -2, "isMethod");
        pushReflectValue(L, handle.doc, n.access);
        lua_setfield(L, -2, "access");
        break;
    }
    case Aux_ClassProperty:
    {
        auto& n = handle.classProp;
        (void)n;
        pushReflectValue(L, handle.doc, n.name);
        lua_setfield(L, -2, "name");
        pushReflectValue(L, handle.doc, n.ty);
        lua_setfield(L, -2, "type");
        break;
    }
    case Aux_ClassMethod:
    {
        auto& n = handle.classMethod;
        (void)n;
        pushReflectValue(L, handle.doc, n.functionName);
        lua_setfield(L, -2, "name");
        pushReflectValue(L, handle.doc, n.function);
        lua_setfield(L, -2, "func");
        break;
    }
    case Aux_Comment:
    {
        auto& n = handle.comment;
        (void)n;
        pushReflectValue(L, handle.doc, handle.comment.type);
        lua_setfield(L, -2, "type");
        pushReflectValue(L, handle.doc, handle.comment.text);
        lua_setfield(L, -2, "text");
        pushReflectValue(L, handle.doc, handle.comment.location);
        lua_setfield(L, -2, "origlocation");
        break;
    }
    case Aux_TableItem:
    {
        auto& n = handle.tableItem;
        (void)n;
        pushReflectValue(L, handle.doc, n.key);
        lua_setfield(L, -2, "key");
        pushReflectValue(L, handle.doc, n.value);
        lua_setfield(L, -2, "value");
        pushReflectValue(L, handle.doc, n.kind);
        lua_setfield(L, -2, "kind");
        break;
    }
    case Aux_TypeList:
    {
        auto& n = handle.typeList;
        (void)n;
        pushReflectValue(L, handle.doc, n.types);
        lua_setfield(L, -2, "types");
        pushReflectValue(L, handle.doc, n.tailType);
        lua_setfield(L, -2, "tailType");
        break;
    }
    case Aux_CstTableItem:
    {
        auto& n = handle.cstTableItem;
        (void)n;
        pushReflectValue(L, handle.doc, n.indexerOpenPosition);
        lua_setfield(L, -2, "indexerOpenPosition");
        pushReflectValue(L, handle.doc, n.indexerClosePosition);
        lua_setfield(L, -2, "indexerClosePosition");
        pushReflectValue(L, handle.doc, n.equalsPosition);
        lua_setfield(L, -2, "equalsPosition");
        pushReflectValue(L, handle.doc, n.separatorPosition);
        lua_setfield(L, -2, "separatorPosition");
        pushReflectValue(L, handle.doc, n.separator);
        lua_setfield(L, -2, "separator");
        break;
    }
    default:
        break;
    }
}

} // namespace Luau
