// Auto-generated by Reflect/generate_reflect_cpp.py. DO NOT EDIT!
#pragma once

#include <vector>
#include "Luau/Cst.h"
#include "Luau/ReflectCommon.h"
#include "Luau/ReflectAstHandler.h"

namespace Luau
{

struct CstNodeClassInfo
{
    const char* kind = nullptr;
    const char* category = "generic";
    bool (*methodHandler)(lua_State* L, CstNodeData& handle, ReflectAtom atom) = nullptr;
    void (*propCollector)(lua_State* L, CstNodeData& handle) = nullptr;
    const Luau::CstNode* (*factory)(Luau::Allocator& alloc) = nullptr;
};

static std::vector<CstNodeClassInfo> s_cstClassTable;

template<typename T>
static void registerCstNodeClass(
    const char* kind,
    bool (*methodHandler)(lua_State* L, CstNodeData& handle, ReflectAtom atom) = nullptr,
    void (*propCollector)(lua_State* L, CstNodeData& handle) = nullptr,
    const Luau::CstNode* (*factory)(Luau::Allocator& alloc) = nullptr
)
{
    int idx = T::CstClassIndex();
    if (size_t(idx) >= s_cstClassTable.size())
    {
        s_cstClassTable.resize(idx + 1, CstNodeClassInfo{"CstNode", "generic", nullptr, nullptr, nullptr});
    }
    s_cstClassTable[idx] = CstNodeClassInfo{kind, "generic", methodHandler, propCollector, factory};
}

const Luau::CstNode* createDefaultCstNode(ReflectAtom atom, Luau::Allocator& alloc)
{
    switch (atom)
    {
    case ReflectAtom::CstAttr:
        return alloc.alloc<Luau::CstAttr>(false);
    case ReflectAtom::CstParametrizedAttr:
        return alloc.alloc<Luau::CstParametrizedAttr>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstExprGroup:
        return alloc.alloc<Luau::CstExprGroup>(Luau::Position::missing());
    case ReflectAtom::CstExprConstantNumber:
        return alloc.alloc<Luau::CstExprConstantNumber>(Luau::AstArray<char>{nullptr, 0});
    case ReflectAtom::CstExprConstantInteger:
        return alloc.alloc<Luau::CstExprConstantInteger>(Luau::AstArray<char>{nullptr, 0});
    case ReflectAtom::CstExprConstantString:
        return alloc.alloc<Luau::CstExprConstantString>(Luau::AstArray<char>{nullptr, 0}, Luau::CstExprConstantString::QuoteStyle::QuotedSingle, 0);
    case ReflectAtom::CstExprCall:
        return alloc.alloc<Luau::CstExprCall>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstExprIndexExpr:
        return alloc.alloc<Luau::CstExprIndexExpr>(Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstExprTable:
        return alloc.alloc<Luau::CstExprTable>(Luau::AstArray<Luau::CstExprTable::Item>{nullptr, 0});
    case ReflectAtom::CstExprOp:
        return alloc.alloc<Luau::CstExprOp>(Luau::Position::missing());
    case ReflectAtom::CstExprTypeAssertion:
        return alloc.alloc<Luau::CstExprTypeAssertion>(Luau::Position::missing());
    case ReflectAtom::CstExprIfElse:
        return alloc.alloc<Luau::CstExprIfElse>(Luau::Position::missing(), Luau::Position::missing(), false);
    case ReflectAtom::CstExprInterpString:
        return alloc.alloc<Luau::CstExprInterpString>(Luau::AstArray<Luau::AstArray<char>>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstStatDo:
        return alloc.alloc<Luau::CstStatDo>(Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstStatRepeat:
        return alloc.alloc<Luau::CstStatRepeat>(Luau::Position::missing());
    case ReflectAtom::CstStatReturn:
        return alloc.alloc<Luau::CstStatReturn>(Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstStatLocal:
        return alloc.alloc<Luau::CstStatLocal>(Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstStatFor:
        return alloc.alloc<Luau::CstStatFor>(Luau::Position::missing(), Luau::Position::missing(), Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstStatForIn:
        return alloc.alloc<Luau::CstStatForIn>(Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstStatAssign:
        return alloc.alloc<Luau::CstStatAssign>(Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstStatCompoundAssign:
        return alloc.alloc<Luau::CstStatCompoundAssign>(Luau::Position::missing());
    case ReflectAtom::CstStatFunction:
        return alloc.alloc<Luau::CstStatFunction>(Luau::Position::missing());
    case ReflectAtom::CstStatLocalFunction:
        return alloc.alloc<Luau::CstStatLocalFunction>(Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstGenericType:
        return alloc.alloc<Luau::CstGenericType>(Luau::Position::missing());
    case ReflectAtom::CstGenericTypePack:
        return alloc.alloc<Luau::CstGenericTypePack>(Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstStatTypeAlias:
        return alloc.alloc<Luau::CstStatTypeAlias>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstStatTypeFunction:
        return alloc.alloc<Luau::CstStatTypeFunction>(Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstTypeReference:
        return alloc.alloc<Luau::CstTypeReference>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing());
    case ReflectAtom::CstTypeTable:
        return alloc.alloc<Luau::CstTypeTable>(Luau::AstArray<Luau::CstTypeTable::Item>{nullptr, 0}, false);
    case ReflectAtom::CstTypeFunction:
        return alloc.alloc<Luau::CstTypeFunction>(Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstTypeTypeof:
        return alloc.alloc<Luau::CstTypeTypeof>(Luau::Position::missing(), Luau::Position::missing());
    case ReflectAtom::CstTypeUnion:
        return alloc.alloc<Luau::CstTypeUnion>(Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstTypeIntersection:
        return alloc.alloc<Luau::CstTypeIntersection>(Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstTypeSingletonString:
        return alloc.alloc<Luau::CstTypeSingletonString>(Luau::AstArray<char>{nullptr, 0}, Luau::CstExprConstantString::QuoteStyle::QuotedSingle, 0);
    case ReflectAtom::CstTypeGroup:
        return alloc.alloc<Luau::CstTypeGroup>(Luau::Position::missing());
    case ReflectAtom::CstTypePackExplicit:
        return alloc.alloc<Luau::CstTypePackExplicit>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
    case ReflectAtom::CstTypePackGeneric:
        return alloc.alloc<Luau::CstTypePackGeneric>(Luau::Position::missing());
    default:
        return nullptr;
    }
}

static const Luau::CstNode* createDefaultCstAttr(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstAttr>(false);
}

static bool handleCstAttrMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstAttr*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::HasAt:
        pushReflectValue(L, handle.doc, n->hasAt);
        return true;
    default:
        return false;
    }
}

static void collectCstAttrProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstAttr*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->hasAt);
    lua_setfield(L, -2, "hasAt");
}

static const Luau::CstNode* createDefaultCstParametrizedAttr(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstParametrizedAttr>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstParametrizedAttrMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstParametrizedAttr*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpenParenPosition:
        pushReflectValue(L, handle.doc, n->openParenPosition);
        return true;
    case ReflectAtom::CloseParenPosition:
        pushReflectValue(L, handle.doc, n->closeParenPosition);
        return true;
    case ReflectAtom::ArgsCommaPositions:
        pushReflectValue(L, handle.doc, n->argsCommaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstParametrizedAttrProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstParametrizedAttr*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->openParenPosition);
    lua_setfield(L, -2, "openParenPosition");
    pushReflectValue(L, handle.doc, n->closeParenPosition);
    lua_setfield(L, -2, "closeParenPosition");
    pushReflectValue(L, handle.doc, n->argsCommaPositions);
    lua_setfield(L, -2, "argsCommaPositions");
}

static const Luau::CstNode* createDefaultCstExprGroup(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprGroup>(Luau::Position::missing());
}

static bool handleCstExprGroupMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprGroup*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::ClosePosition:
        pushReflectValue(L, handle.doc, n->closePosition);
        return true;
    default:
        return false;
    }
}

static void collectCstExprGroupProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprGroup*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->closePosition);
    lua_setfield(L, -2, "closePosition");
}

static const Luau::CstNode* createDefaultCstExprConstantNumber(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprConstantNumber>(Luau::AstArray<char>{nullptr, 0});
}

static bool handleCstExprConstantNumberMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprConstantNumber*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::Value:
        pushReflectValue(L, handle.doc, n->value);
        return true;
    default:
        return false;
    }
}

static void collectCstExprConstantNumberProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprConstantNumber*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->value);
    lua_setfield(L, -2, "value");
}

static const Luau::CstNode* createDefaultCstExprConstantInteger(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprConstantInteger>(Luau::AstArray<char>{nullptr, 0});
}

static bool handleCstExprConstantIntegerMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprConstantInteger*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::Value:
        pushReflectValue(L, handle.doc, n->value);
        return true;
    default:
        return false;
    }
}

static void collectCstExprConstantIntegerProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprConstantInteger*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->value);
    lua_setfield(L, -2, "value");
}

static const Luau::CstNode* createDefaultCstExprConstantString(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprConstantString>(Luau::AstArray<char>{nullptr, 0}, Luau::CstExprConstantString::QuoteStyle::QuotedSingle, 0);
}

static bool handleCstExprConstantStringMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprConstantString*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::QuoteStyle:
        pushReflectValue(L, handle.doc, n->quoteStyle);
        return true;
    case ReflectAtom::BlockDepth:
        pushReflectValue(L, handle.doc, n->blockDepth);
        return true;
    case ReflectAtom::SourceString:
        pushReflectValue(L, handle.doc, n->sourceString);
        return true;
    default:
        return false;
    }
}

static void collectCstExprConstantStringProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprConstantString*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->quoteStyle);
    lua_setfield(L, -2, "quoteStyle");
    pushReflectValue(L, handle.doc, n->blockDepth);
    lua_setfield(L, -2, "blockDepth");
    pushReflectValue(L, handle.doc, n->sourceString);
    lua_setfield(L, -2, "sourceString");
}

static const Luau::CstNode* createDefaultCstExprCall(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprCall>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstExprCallMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprCall*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpenParens:
        pushReflectValue(L, handle.doc, n->openParens);
        return true;
    case ReflectAtom::CloseParens:
        pushReflectValue(L, handle.doc, n->closeParens);
        return true;
    case ReflectAtom::CommaPositions:
        pushReflectValue(L, handle.doc, n->commaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstExprCallProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprCall*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->openParens);
    lua_setfield(L, -2, "openParens");
    pushReflectValue(L, handle.doc, n->closeParens);
    lua_setfield(L, -2, "closeParens");
    pushReflectValue(L, handle.doc, n->commaPositions);
    lua_setfield(L, -2, "commaPositions");
}

static const Luau::CstNode* createDefaultCstExprIndexExpr(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprIndexExpr>(Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstExprIndexExprMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprIndexExpr*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpenBracketPosition:
        pushReflectValue(L, handle.doc, n->openBracketPosition);
        return true;
    case ReflectAtom::CloseBracketPosition:
        pushReflectValue(L, handle.doc, n->closeBracketPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstExprIndexExprProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprIndexExpr*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->openBracketPosition);
    lua_setfield(L, -2, "openBracketPosition");
    pushReflectValue(L, handle.doc, n->closeBracketPosition);
    lua_setfield(L, -2, "closeBracketPosition");
}

static const Luau::CstNode* createDefaultCstExprFunction(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprFunction>();
}

static bool handleCstExprFunctionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprFunction*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::FunctionKeywordPosition:
        pushReflectValue(L, handle.doc, n->functionKeywordPosition);
        return true;
    case ReflectAtom::OpenGenericsPosition:
        pushReflectValue(L, handle.doc, n->openGenericsPosition);
        return true;
    case ReflectAtom::GenericsCommaPositions:
        pushReflectValue(L, handle.doc, n->genericsCommaPositions);
        return true;
    case ReflectAtom::CloseGenericsPosition:
        pushReflectValue(L, handle.doc, n->closeGenericsPosition);
        return true;
    case ReflectAtom::ArgsAnnotationColonPositions:
        pushReflectValue(L, handle.doc, n->argsAnnotationColonPositions);
        return true;
    case ReflectAtom::ArgsCommaPositions:
        pushReflectValue(L, handle.doc, n->argsCommaPositions);
        return true;
    case ReflectAtom::VarargAnnotationColonPosition:
        pushReflectValue(L, handle.doc, n->varargAnnotationColonPosition);
        return true;
    case ReflectAtom::ReturnSpecifierPosition:
        pushReflectValue(L, handle.doc, n->returnSpecifierPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstExprFunctionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprFunction*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->functionKeywordPosition);
    lua_setfield(L, -2, "functionKeywordPosition");
    pushReflectValue(L, handle.doc, n->openGenericsPosition);
    lua_setfield(L, -2, "openGenericsPosition");
    pushReflectValue(L, handle.doc, n->genericsCommaPositions);
    lua_setfield(L, -2, "genericsCommaPositions");
    pushReflectValue(L, handle.doc, n->closeGenericsPosition);
    lua_setfield(L, -2, "closeGenericsPosition");
    pushReflectValue(L, handle.doc, n->argsAnnotationColonPositions);
    lua_setfield(L, -2, "argsAnnotationColonPositions");
    pushReflectValue(L, handle.doc, n->argsCommaPositions);
    lua_setfield(L, -2, "argsCommaPositions");
    pushReflectValue(L, handle.doc, n->varargAnnotationColonPosition);
    lua_setfield(L, -2, "varargAnnotationColonPosition");
    pushReflectValue(L, handle.doc, n->returnSpecifierPosition);
    lua_setfield(L, -2, "returnSpecifierPosition");
}

static const Luau::CstNode* createDefaultCstExprTable(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprTable>(Luau::AstArray<Luau::CstExprTable::Item>{nullptr, 0});
}

static bool handleCstExprTableMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprTable*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::Items:
        pushReflectValue(L, handle.doc, n->items);
        return true;
    default:
        return false;
    }
}

static void collectCstExprTableProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprTable*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->items);
    lua_setfield(L, -2, "items");
}

static const Luau::CstNode* createDefaultCstExprOp(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprOp>(Luau::Position::missing());
}

static bool handleCstExprOpMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprOp*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpPosition:
        pushReflectValue(L, handle.doc, n->opPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstExprOpProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprOp*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->opPosition);
    lua_setfield(L, -2, "opPosition");
}

static const Luau::CstNode* createDefaultCstExprTypeAssertion(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprTypeAssertion>(Luau::Position::missing());
}

static bool handleCstExprTypeAssertionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprTypeAssertion*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpPosition:
        pushReflectValue(L, handle.doc, n->opPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstExprTypeAssertionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprTypeAssertion*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->opPosition);
    lua_setfield(L, -2, "opPosition");
}

static const Luau::CstNode* createDefaultCstExprIfElse(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprIfElse>(Luau::Position::missing(), Luau::Position::missing(), false);
}

static bool handleCstExprIfElseMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprIfElse*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::IsElseIf:
        pushReflectValue(L, handle.doc, n->isElseIf);
        return true;
    case ReflectAtom::ThenPosition:
        pushReflectValue(L, handle.doc, n->thenPosition);
        return true;
    case ReflectAtom::ElsePosition:
        pushReflectValue(L, handle.doc, n->elsePosition);
        return true;
    default:
        return false;
    }
}

static void collectCstExprIfElseProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprIfElse*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->isElseIf);
    lua_setfield(L, -2, "isElseIf");
    pushReflectValue(L, handle.doc, n->thenPosition);
    lua_setfield(L, -2, "thenPosition");
    pushReflectValue(L, handle.doc, n->elsePosition);
    lua_setfield(L, -2, "elsePosition");
}

static const Luau::CstNode* createDefaultCstExprInterpString(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprInterpString>(Luau::AstArray<Luau::AstArray<char>>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstExprInterpStringMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstExprInterpString*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::CommaPositions:
        pushReflectValue(L, handle.doc, n->stringPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstExprInterpStringProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstExprInterpString*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->stringPositions);
    lua_setfield(L, -2, "commaPositions");
}

static const Luau::CstNode* createDefaultCstExprExplicitTypeInstantiation(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstExprExplicitTypeInstantiation>(Luau::CstTypeInstantiation{});
}

static bool handleCstExprExplicitTypeInstantiationMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    return false;
}

static void collectCstExprExplicitTypeInstantiationProps(lua_State* L, CstNodeData& handle)
{
}

static const Luau::CstNode* createDefaultCstStatDo(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatDo>(Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstStatDoMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatDo*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::StatsStartPosition:
        pushReflectValue(L, handle.doc, n->statsStartPosition);
        return true;
    case ReflectAtom::EndPosition:
        pushReflectValue(L, handle.doc, n->endPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatDoProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatDo*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->statsStartPosition);
    lua_setfield(L, -2, "statsStartPosition");
    pushReflectValue(L, handle.doc, n->endPosition);
    lua_setfield(L, -2, "endPosition");
}

static const Luau::CstNode* createDefaultCstStatRepeat(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatRepeat>(Luau::Position::missing());
}

static bool handleCstStatRepeatMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatRepeat*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::UntilPosition:
        pushReflectValue(L, handle.doc, n->untilPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatRepeatProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatRepeat*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->untilPosition);
    lua_setfield(L, -2, "untilPosition");
}

static const Luau::CstNode* createDefaultCstStatReturn(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatReturn>(Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstStatReturnMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatReturn*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::CommaPositions:
        pushReflectValue(L, handle.doc, n->commaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstStatReturnProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatReturn*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->commaPositions);
    lua_setfield(L, -2, "commaPositions");
}

static const Luau::CstNode* createDefaultCstStatLocal(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatLocal>(Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstStatLocalMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatLocal*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::VarsAnnotationColonPositions:
        pushReflectValue(L, handle.doc, n->varsAnnotationColonPositions);
        return true;
    case ReflectAtom::VarsCommaPositions:
        pushReflectValue(L, handle.doc, n->varsCommaPositions);
        return true;
    case ReflectAtom::ValuesCommaPositions:
        pushReflectValue(L, handle.doc, n->valuesCommaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstStatLocalProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatLocal*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->varsAnnotationColonPositions);
    lua_setfield(L, -2, "varsAnnotationColonPositions");
    pushReflectValue(L, handle.doc, n->varsCommaPositions);
    lua_setfield(L, -2, "varsCommaPositions");
    pushReflectValue(L, handle.doc, n->valuesCommaPositions);
    lua_setfield(L, -2, "valuesCommaPositions");
}

static const Luau::CstNode* createDefaultCstStatFor(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatFor>(Luau::Position::missing(), Luau::Position::missing(), Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstStatForMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatFor*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::AnnotationColonPosition:
        pushReflectValue(L, handle.doc, n->annotationColonPosition);
        return true;
    case ReflectAtom::EqualsPosition:
        pushReflectValue(L, handle.doc, n->equalsPosition);
        return true;
    case ReflectAtom::EndCommaPosition:
        pushReflectValue(L, handle.doc, n->endCommaPosition);
        return true;
    case ReflectAtom::StepCommaPosition:
        pushReflectValue(L, handle.doc, n->stepCommaPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatForProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatFor*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->annotationColonPosition);
    lua_setfield(L, -2, "annotationColonPosition");
    pushReflectValue(L, handle.doc, n->equalsPosition);
    lua_setfield(L, -2, "equalsPosition");
    pushReflectValue(L, handle.doc, n->endCommaPosition);
    lua_setfield(L, -2, "endCommaPosition");
    pushReflectValue(L, handle.doc, n->stepCommaPosition);
    lua_setfield(L, -2, "stepCommaPosition");
}

static const Luau::CstNode* createDefaultCstStatForIn(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatForIn>(Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstStatForInMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatForIn*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::VarsAnnotationColonPositions:
        pushReflectValue(L, handle.doc, n->varsAnnotationColonPositions);
        return true;
    case ReflectAtom::VarsCommaPositions:
        pushReflectValue(L, handle.doc, n->varsCommaPositions);
        return true;
    case ReflectAtom::ValuesCommaPositions:
        pushReflectValue(L, handle.doc, n->valuesCommaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstStatForInProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatForIn*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->varsAnnotationColonPositions);
    lua_setfield(L, -2, "varsAnnotationColonPositions");
    pushReflectValue(L, handle.doc, n->varsCommaPositions);
    lua_setfield(L, -2, "varsCommaPositions");
    pushReflectValue(L, handle.doc, n->valuesCommaPositions);
    lua_setfield(L, -2, "valuesCommaPositions");
}

static const Luau::CstNode* createDefaultCstStatAssign(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatAssign>(Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstStatAssignMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatAssign*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::VarsCommaPositions:
        pushReflectValue(L, handle.doc, n->varsCommaPositions);
        return true;
    case ReflectAtom::EqualsPosition:
        pushReflectValue(L, handle.doc, n->equalsPosition);
        return true;
    case ReflectAtom::ValuesCommaPositions:
        pushReflectValue(L, handle.doc, n->valuesCommaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstStatAssignProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatAssign*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->varsCommaPositions);
    lua_setfield(L, -2, "varsCommaPositions");
    pushReflectValue(L, handle.doc, n->equalsPosition);
    lua_setfield(L, -2, "equalsPosition");
    pushReflectValue(L, handle.doc, n->valuesCommaPositions);
    lua_setfield(L, -2, "valuesCommaPositions");
}

static const Luau::CstNode* createDefaultCstStatCompoundAssign(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatCompoundAssign>(Luau::Position::missing());
}

static bool handleCstStatCompoundAssignMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatCompoundAssign*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpPosition:
        pushReflectValue(L, handle.doc, n->opPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatCompoundAssignProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatCompoundAssign*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->opPosition);
    lua_setfield(L, -2, "opPosition");
}

static const Luau::CstNode* createDefaultCstStatFunction(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatFunction>(Luau::Position::missing());
}

static bool handleCstStatFunctionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatFunction*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::FunctionKeywordPosition:
        pushReflectValue(L, handle.doc, n->functionKeywordPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatFunctionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatFunction*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->functionKeywordPosition);
    lua_setfield(L, -2, "functionKeywordPosition");
}

static const Luau::CstNode* createDefaultCstStatLocalFunction(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatLocalFunction>(Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstStatLocalFunctionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatLocalFunction*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::LocalKeywordPosition:
        pushReflectValue(L, handle.doc, n->localKeywordPosition);
        return true;
    case ReflectAtom::FunctionKeywordPosition:
        pushReflectValue(L, handle.doc, n->functionKeywordPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatLocalFunctionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatLocalFunction*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->localKeywordPosition);
    lua_setfield(L, -2, "localKeywordPosition");
    pushReflectValue(L, handle.doc, n->functionKeywordPosition);
    lua_setfield(L, -2, "functionKeywordPosition");
}

static const Luau::CstNode* createDefaultCstGenericType(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstGenericType>(Luau::Position::missing());
}

static bool handleCstGenericTypeMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstGenericType*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::DefaultEqualsPosition:
        pushReflectValue(L, handle.doc, n->defaultEqualsPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstGenericTypeProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstGenericType*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->defaultEqualsPosition);
    lua_setfield(L, -2, "defaultEqualsPosition");
}

static const Luau::CstNode* createDefaultCstGenericTypePack(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstGenericTypePack>(Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstGenericTypePackMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstGenericTypePack*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::EllipsisPosition:
        pushReflectValue(L, handle.doc, n->ellipsisPosition);
        return true;
    case ReflectAtom::DefaultEqualsPosition:
        pushReflectValue(L, handle.doc, n->defaultEqualsPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstGenericTypePackProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstGenericTypePack*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->ellipsisPosition);
    lua_setfield(L, -2, "ellipsisPosition");
    pushReflectValue(L, handle.doc, n->defaultEqualsPosition);
    lua_setfield(L, -2, "defaultEqualsPosition");
}

static const Luau::CstNode* createDefaultCstStatTypeAlias(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatTypeAlias>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstStatTypeAliasMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatTypeAlias*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::TypeKeywordPosition:
        pushReflectValue(L, handle.doc, n->typeKeywordPosition);
        return true;
    case ReflectAtom::GenericsOpenPosition:
        pushReflectValue(L, handle.doc, n->genericsOpenPosition);
        return true;
    case ReflectAtom::GenericsCommaPositions:
        pushReflectValue(L, handle.doc, n->genericsCommaPositions);
        return true;
    case ReflectAtom::GenericsClosePosition:
        pushReflectValue(L, handle.doc, n->genericsClosePosition);
        return true;
    case ReflectAtom::EqualsPosition:
        pushReflectValue(L, handle.doc, n->equalsPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatTypeAliasProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatTypeAlias*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->typeKeywordPosition);
    lua_setfield(L, -2, "typeKeywordPosition");
    pushReflectValue(L, handle.doc, n->genericsOpenPosition);
    lua_setfield(L, -2, "genericsOpenPosition");
    pushReflectValue(L, handle.doc, n->genericsCommaPositions);
    lua_setfield(L, -2, "genericsCommaPositions");
    pushReflectValue(L, handle.doc, n->genericsClosePosition);
    lua_setfield(L, -2, "genericsClosePosition");
    pushReflectValue(L, handle.doc, n->equalsPosition);
    lua_setfield(L, -2, "equalsPosition");
}

static const Luau::CstNode* createDefaultCstStatTypeFunction(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstStatTypeFunction>(Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstStatTypeFunctionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstStatTypeFunction*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::TypeKeywordPosition:
        pushReflectValue(L, handle.doc, n->typeKeywordPosition);
        return true;
    case ReflectAtom::FunctionKeywordPosition:
        pushReflectValue(L, handle.doc, n->functionKeywordPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstStatTypeFunctionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstStatTypeFunction*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->typeKeywordPosition);
    lua_setfield(L, -2, "typeKeywordPosition");
    pushReflectValue(L, handle.doc, n->functionKeywordPosition);
    lua_setfield(L, -2, "functionKeywordPosition");
}

static const Luau::CstNode* createDefaultCstTypeReference(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeReference>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing());
}

static bool handleCstTypeReferenceMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeReference*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::PrefixPointPosition:
        pushReflectValue(L, handle.doc, n->prefixPointPosition);
        return true;
    case ReflectAtom::OpenParametersPosition:
        pushReflectValue(L, handle.doc, n->openParametersPosition);
        return true;
    case ReflectAtom::ParametersCommaPositions:
        pushReflectValue(L, handle.doc, n->parametersCommaPositions);
        return true;
    case ReflectAtom::CloseParametersPosition:
        pushReflectValue(L, handle.doc, n->closeParametersPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeReferenceProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeReference*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->prefixPointPosition);
    lua_setfield(L, -2, "prefixPointPosition");
    pushReflectValue(L, handle.doc, n->openParametersPosition);
    lua_setfield(L, -2, "openParametersPosition");
    pushReflectValue(L, handle.doc, n->parametersCommaPositions);
    lua_setfield(L, -2, "parametersCommaPositions");
    pushReflectValue(L, handle.doc, n->closeParametersPosition);
    lua_setfield(L, -2, "closeParametersPosition");
}

static const Luau::CstNode* createDefaultCstTypeTable(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeTable>(Luau::AstArray<Luau::CstTypeTable::Item>{nullptr, 0}, false);
}

static bool handleCstTypeTableMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeTable*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::IsArray:
        pushReflectValue(L, handle.doc, n->isArray);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeTableProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeTable*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->isArray);
    lua_setfield(L, -2, "isArray");
}

static const Luau::CstNode* createDefaultCstTypeFunction(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeFunction>(Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::AstArray<Luau::Position>{nullptr, 0}, Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstTypeFunctionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeFunction*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpenGenericsPosition:
        pushReflectValue(L, handle.doc, n->openGenericsPosition);
        return true;
    case ReflectAtom::GenericsCommaPositions:
        pushReflectValue(L, handle.doc, n->genericsCommaPositions);
        return true;
    case ReflectAtom::CloseGenericsPosition:
        pushReflectValue(L, handle.doc, n->closeGenericsPosition);
        return true;
    case ReflectAtom::OpenArgsPosition:
        pushReflectValue(L, handle.doc, n->openArgsPosition);
        return true;
    case ReflectAtom::ArgumentNameColonPositions:
        pushReflectValue(L, handle.doc, n->argumentNameColonPositions);
        return true;
    case ReflectAtom::ArgumentsCommaPositions:
        pushReflectValue(L, handle.doc, n->argumentsCommaPositions);
        return true;
    case ReflectAtom::CloseArgsPosition:
        pushReflectValue(L, handle.doc, n->closeArgsPosition);
        return true;
    case ReflectAtom::ReturnArrowPosition:
        pushReflectValue(L, handle.doc, n->returnArrowPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeFunctionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeFunction*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->openGenericsPosition);
    lua_setfield(L, -2, "openGenericsPosition");
    pushReflectValue(L, handle.doc, n->genericsCommaPositions);
    lua_setfield(L, -2, "genericsCommaPositions");
    pushReflectValue(L, handle.doc, n->closeGenericsPosition);
    lua_setfield(L, -2, "closeGenericsPosition");
    pushReflectValue(L, handle.doc, n->openArgsPosition);
    lua_setfield(L, -2, "openArgsPosition");
    pushReflectValue(L, handle.doc, n->argumentNameColonPositions);
    lua_setfield(L, -2, "argumentNameColonPositions");
    pushReflectValue(L, handle.doc, n->argumentsCommaPositions);
    lua_setfield(L, -2, "argumentsCommaPositions");
    pushReflectValue(L, handle.doc, n->closeArgsPosition);
    lua_setfield(L, -2, "closeArgsPosition");
    pushReflectValue(L, handle.doc, n->returnArrowPosition);
    lua_setfield(L, -2, "returnArrowPosition");
}

static const Luau::CstNode* createDefaultCstTypeTypeof(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeTypeof>(Luau::Position::missing(), Luau::Position::missing());
}

static bool handleCstTypeTypeofMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeTypeof*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpenPosition:
        pushReflectValue(L, handle.doc, n->openPosition);
        return true;
    case ReflectAtom::ClosePosition:
        pushReflectValue(L, handle.doc, n->closePosition);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeTypeofProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeTypeof*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->openPosition);
    lua_setfield(L, -2, "openPosition");
    pushReflectValue(L, handle.doc, n->closePosition);
    lua_setfield(L, -2, "closePosition");
}

static const Luau::CstNode* createDefaultCstTypeUnion(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeUnion>(Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstTypeUnionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeUnion*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::LeadingPosition:
        pushReflectValue(L, handle.doc, n->leadingPosition);
        return true;
    case ReflectAtom::SeparatorPositions:
        pushReflectValue(L, handle.doc, n->separatorPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeUnionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeUnion*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->leadingPosition);
    lua_setfield(L, -2, "leadingPosition");
    pushReflectValue(L, handle.doc, n->separatorPositions);
    lua_setfield(L, -2, "separatorPositions");
}

static const Luau::CstNode* createDefaultCstTypeIntersection(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeIntersection>(Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstTypeIntersectionMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeIntersection*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::LeadingPosition:
        pushReflectValue(L, handle.doc, n->leadingPosition);
        return true;
    case ReflectAtom::SeparatorPositions:
        pushReflectValue(L, handle.doc, n->separatorPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeIntersectionProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeIntersection*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->leadingPosition);
    lua_setfield(L, -2, "leadingPosition");
    pushReflectValue(L, handle.doc, n->separatorPositions);
    lua_setfield(L, -2, "separatorPositions");
}

static const Luau::CstNode* createDefaultCstTypeSingletonString(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeSingletonString>(Luau::AstArray<char>{nullptr, 0}, Luau::CstExprConstantString::QuoteStyle::QuotedSingle, 0);
}

static bool handleCstTypeSingletonStringMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeSingletonString*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::QuoteStyle:
        pushReflectValue(L, handle.doc, n->quoteStyle);
        return true;
    case ReflectAtom::BlockDepth:
        pushReflectValue(L, handle.doc, n->blockDepth);
        return true;
    case ReflectAtom::SourceString:
        pushReflectValue(L, handle.doc, n->sourceString);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeSingletonStringProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeSingletonString*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->quoteStyle);
    lua_setfield(L, -2, "quoteStyle");
    pushReflectValue(L, handle.doc, n->blockDepth);
    lua_setfield(L, -2, "blockDepth");
    pushReflectValue(L, handle.doc, n->sourceString);
    lua_setfield(L, -2, "sourceString");
}

static const Luau::CstNode* createDefaultCstTypeGroup(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypeGroup>(Luau::Position::missing());
}

static bool handleCstTypeGroupMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypeGroup*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::ClosePosition:
        pushReflectValue(L, handle.doc, n->closePosition);
        return true;
    default:
        return false;
    }
}

static void collectCstTypeGroupProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypeGroup*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->closePosition);
    lua_setfield(L, -2, "closePosition");
}

static const Luau::CstNode* createDefaultCstTypePackExplicit(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypePackExplicit>(Luau::Position::missing(), Luau::Position::missing(), Luau::AstArray<Luau::Position>{nullptr, 0});
}

static bool handleCstTypePackExplicitMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypePackExplicit*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::OpenParenthesesPosition:
        pushReflectValue(L, handle.doc, n->openParenthesesPosition);
        return true;
    case ReflectAtom::CloseParenthesesPosition:
        pushReflectValue(L, handle.doc, n->closeParenthesesPosition);
        return true;
    case ReflectAtom::CommaPositions:
        pushReflectValue(L, handle.doc, n->commaPositions);
        return true;
    default:
        return false;
    }
}

static void collectCstTypePackExplicitProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypePackExplicit*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->openParenthesesPosition);
    lua_setfield(L, -2, "openParenthesesPosition");
    pushReflectValue(L, handle.doc, n->closeParenthesesPosition);
    lua_setfield(L, -2, "closeParenthesesPosition");
    pushReflectValue(L, handle.doc, n->commaPositions);
    lua_setfield(L, -2, "commaPositions");
}

static const Luau::CstNode* createDefaultCstTypePackGeneric(Luau::Allocator& alloc)
{
    return alloc.alloc<Luau::CstTypePackGeneric>(Luau::Position::missing());
}

static bool handleCstTypePackGenericMethods(lua_State* L, CstNodeData& handle, ReflectAtom atom)
{
    auto* n = static_cast<const Luau::CstTypePackGeneric*>(handle.node);
    switch (atom)
    {
    case ReflectAtom::EllipsisPosition:
        pushReflectValue(L, handle.doc, n->ellipsisPosition);
        return true;
    default:
        return false;
    }
}

static void collectCstTypePackGenericProps(lua_State* L, CstNodeData& handle)
{
    auto* n = static_cast<const Luau::CstTypePackGeneric*>(handle.node);
    (void)n;
    pushReflectValue(L, handle.doc, n->ellipsisPosition);
    lua_setfield(L, -2, "ellipsisPosition");
}

static void registerCstNodeClasses()
{
    registerCstNodeClass<Luau::CstAttr>("CstAttr", handleCstAttrMethods, collectCstAttrProps, createDefaultCstAttr);
    registerCstNodeClass<Luau::CstParametrizedAttr>("CstParametrizedAttr", handleCstParametrizedAttrMethods, collectCstParametrizedAttrProps, createDefaultCstParametrizedAttr);
    registerCstNodeClass<Luau::CstExprGroup>("CstExprGroup", handleCstExprGroupMethods, collectCstExprGroupProps, createDefaultCstExprGroup);
    registerCstNodeClass<Luau::CstExprConstantNumber>("CstExprConstantNumber", handleCstExprConstantNumberMethods, collectCstExprConstantNumberProps, createDefaultCstExprConstantNumber);
    registerCstNodeClass<Luau::CstExprConstantInteger>("CstExprConstantInteger", handleCstExprConstantIntegerMethods, collectCstExprConstantIntegerProps, createDefaultCstExprConstantInteger);
    registerCstNodeClass<Luau::CstExprConstantString>("CstExprConstantString", handleCstExprConstantStringMethods, collectCstExprConstantStringProps, createDefaultCstExprConstantString);
    registerCstNodeClass<Luau::CstExprCall>("CstExprCall", handleCstExprCallMethods, collectCstExprCallProps, createDefaultCstExprCall);
    registerCstNodeClass<Luau::CstExprIndexExpr>("CstExprIndexExpr", handleCstExprIndexExprMethods, collectCstExprIndexExprProps, createDefaultCstExprIndexExpr);
    registerCstNodeClass<Luau::CstExprFunction>("CstExprFunction", handleCstExprFunctionMethods, collectCstExprFunctionProps, createDefaultCstExprFunction);
    registerCstNodeClass<Luau::CstExprTable>("CstExprTable", handleCstExprTableMethods, collectCstExprTableProps, createDefaultCstExprTable);
    registerCstNodeClass<Luau::CstExprOp>("CstExprOp", handleCstExprOpMethods, collectCstExprOpProps, createDefaultCstExprOp);
    registerCstNodeClass<Luau::CstExprTypeAssertion>("CstExprTypeAssertion", handleCstExprTypeAssertionMethods, collectCstExprTypeAssertionProps, createDefaultCstExprTypeAssertion);
    registerCstNodeClass<Luau::CstExprIfElse>("CstExprIfElse", handleCstExprIfElseMethods, collectCstExprIfElseProps, createDefaultCstExprIfElse);
    registerCstNodeClass<Luau::CstExprInterpString>("CstExprInterpString", handleCstExprInterpStringMethods, collectCstExprInterpStringProps, createDefaultCstExprInterpString);
    registerCstNodeClass<Luau::CstExprExplicitTypeInstantiation>("CstExprExplicitTypeInstantiation", handleCstExprExplicitTypeInstantiationMethods, collectCstExprExplicitTypeInstantiationProps, createDefaultCstExprExplicitTypeInstantiation);
    registerCstNodeClass<Luau::CstStatDo>("CstStatDo", handleCstStatDoMethods, collectCstStatDoProps, createDefaultCstStatDo);
    registerCstNodeClass<Luau::CstStatRepeat>("CstStatRepeat", handleCstStatRepeatMethods, collectCstStatRepeatProps, createDefaultCstStatRepeat);
    registerCstNodeClass<Luau::CstStatReturn>("CstStatReturn", handleCstStatReturnMethods, collectCstStatReturnProps, createDefaultCstStatReturn);
    registerCstNodeClass<Luau::CstStatLocal>("CstStatLocal", handleCstStatLocalMethods, collectCstStatLocalProps, createDefaultCstStatLocal);
    registerCstNodeClass<Luau::CstStatFor>("CstStatFor", handleCstStatForMethods, collectCstStatForProps, createDefaultCstStatFor);
    registerCstNodeClass<Luau::CstStatForIn>("CstStatForIn", handleCstStatForInMethods, collectCstStatForInProps, createDefaultCstStatForIn);
    registerCstNodeClass<Luau::CstStatAssign>("CstStatAssign", handleCstStatAssignMethods, collectCstStatAssignProps, createDefaultCstStatAssign);
    registerCstNodeClass<Luau::CstStatCompoundAssign>("CstStatCompoundAssign", handleCstStatCompoundAssignMethods, collectCstStatCompoundAssignProps, createDefaultCstStatCompoundAssign);
    registerCstNodeClass<Luau::CstStatFunction>("CstStatFunction", handleCstStatFunctionMethods, collectCstStatFunctionProps, createDefaultCstStatFunction);
    registerCstNodeClass<Luau::CstStatLocalFunction>("CstStatLocalFunction", handleCstStatLocalFunctionMethods, collectCstStatLocalFunctionProps, createDefaultCstStatLocalFunction);
    registerCstNodeClass<Luau::CstGenericType>("CstGenericType", handleCstGenericTypeMethods, collectCstGenericTypeProps, createDefaultCstGenericType);
    registerCstNodeClass<Luau::CstGenericTypePack>("CstGenericTypePack", handleCstGenericTypePackMethods, collectCstGenericTypePackProps, createDefaultCstGenericTypePack);
    registerCstNodeClass<Luau::CstStatTypeAlias>("CstStatTypeAlias", handleCstStatTypeAliasMethods, collectCstStatTypeAliasProps, createDefaultCstStatTypeAlias);
    registerCstNodeClass<Luau::CstStatTypeFunction>("CstStatTypeFunction", handleCstStatTypeFunctionMethods, collectCstStatTypeFunctionProps, createDefaultCstStatTypeFunction);
    registerCstNodeClass<Luau::CstTypeReference>("CstTypeReference", handleCstTypeReferenceMethods, collectCstTypeReferenceProps, createDefaultCstTypeReference);
    registerCstNodeClass<Luau::CstTypeTable>("CstTypeTable", handleCstTypeTableMethods, collectCstTypeTableProps, createDefaultCstTypeTable);
    registerCstNodeClass<Luau::CstTypeFunction>("CstTypeFunction", handleCstTypeFunctionMethods, collectCstTypeFunctionProps, createDefaultCstTypeFunction);
    registerCstNodeClass<Luau::CstTypeTypeof>("CstTypeTypeof", handleCstTypeTypeofMethods, collectCstTypeTypeofProps, createDefaultCstTypeTypeof);
    registerCstNodeClass<Luau::CstTypeUnion>("CstTypeUnion", handleCstTypeUnionMethods, collectCstTypeUnionProps, createDefaultCstTypeUnion);
    registerCstNodeClass<Luau::CstTypeIntersection>("CstTypeIntersection", handleCstTypeIntersectionMethods, collectCstTypeIntersectionProps, createDefaultCstTypeIntersection);
    registerCstNodeClass<Luau::CstTypeSingletonString>("CstTypeSingletonString", handleCstTypeSingletonStringMethods, collectCstTypeSingletonStringProps, createDefaultCstTypeSingletonString);
    registerCstNodeClass<Luau::CstTypeGroup>("CstTypeGroup", handleCstTypeGroupMethods, collectCstTypeGroupProps, createDefaultCstTypeGroup);
    registerCstNodeClass<Luau::CstTypePackExplicit>("CstTypePackExplicit", handleCstTypePackExplicitMethods, collectCstTypePackExplicitProps, createDefaultCstTypePackExplicit);
    registerCstNodeClass<Luau::CstTypePackGeneric>("CstTypePackGeneric", handleCstTypePackGenericMethods, collectCstTypePackGenericProps, createDefaultCstTypePackGeneric);
}

} // namespace Luau
